In [2]:
import numpy as np
import pandas as pd

In [4]:
score={
    "EDA":[99,67,89,79,69,70,89,90],
    "PRVS":[99,67,89,79,69,70,89,90],
    "CAM":[99,67,89,79,69,70,89,90],
    "DAA":[99,67,89,79,69,70,89,90],
}
score
df = pd.DataFrame(score)
df

   EDA  PRVS  CAM  DAA
0   99    99   99   99
1   67    67   67   67
2   89    89   89   89
3   79    79   79   79
4   69    69   69   69
5   70    70   70   70
6   89    89   89   89
7   90    90   90   90

In [6]:
df["AVERAGE"]=np.mean(df,axis=1)
df

   EDA  PRVS  CAM  DAA  AVERAGE
0   99    99   99   99     99.0
1   67    67   67   67     67.0
2   89    89   89   89     89.0
3   79    79   79   79     79.0
4   69    69   69   69     69.0
5   70    70   70   70     70.0
6   89    89   89   89     89.0
7   90    90   90   90     90.0

In [ ]:
for i in df.index:
    df.iloc[i,4]=np.mean(df)