<div align="center">

# MIT Vishwaprayag University, Solapur

## EDA & DV — Assignment 3
#### Healthcare Dataset (Stroke Risk Data)

### Course: B.Tech Semester-III  
</div>


| | |
|:--|:--|
| **Total Marks** | 70 |
| **Dataset** | `healthcare.csv` (place it in the **same folder** as this notebook) |

---

### About this assignment
A hospital has given you a patient dataset and asked you to **check its quality, clean it, and find out what it can (and cannot) tell us** about stroke. The tasks move from basic exploration to open-ended analysis, using the Pandas skills from Labs 11-15 (Series/DataFrame, `loc`/`iloc`, `read_csv`, handling missing values, `describe`, filtering, `groupby`/`agg`, saving files).


### The dataset (data dictionary)
Each row is one patient record.

| Column | Meaning |
|:--|:--|
| `id` | Patient identifier |
| `gender` | Patient's gender |
| `age` | Age in **years** (infants are recorded as fractions, e.g. 0.08) |
| `hypertension` | 1 = patient has high blood pressure, 0 = no |
| `heart_disease` | 1 = patient has heart disease, 0 = no |
| `ever_married` | Whether the patient has ever been married (Yes/No) |
| `work_type` | Type of work (Private, Self-employed, Govt_job, children, Never_worked) |
| `Residence_type` | Rural or Urban |
| `avg_glucose_level` | Average blood glucose level (mg/dL) |
| `bmi` | Body Mass Index (kg/m²) |
| `smoking_status` | never smoked / formerly smoked / smokes / Unknown |
| `stroke` | 1 = patient had a stroke, 0 = no |

### Instructions
1. Write your code in the **code cell** below each question and your written answers in the **markdown cell** (double-click a cell to edit it; press `Shift+Enter` to run/render it).
2. Every question states **what to do**, **why it matters** and the **expected output**. Read all three.
3. For *justify / explain / interpret* parts: write **in your own words and in simple language**, and back every claim with a **number from your own output**. Answers that make claims the data cannot support will lose marks.
4. In the cleaning section there is often **more than one acceptable answer**. Marks are given for *reasoning backed by evidence*, not for guessing the 'expected' method.
5. Add short `#` comments to your code so a reader can follow your thinking. Code you cannot explain may be questioned in a viva.
6. A few helpful methods were not shown in class. They are listed in the reference box below. You may also use the Pandas documentation (`help(pd.DataFrame.method_name)`).
7. Before submitting: **Kernel → Restart & Run All** and make sure the notebook runs from top to bottom without errors. Save as `<RollNo>_EDA_Assignment-3.ipynb`.

> **Marking guide:** correct and efficient Pandas code · clear, evidence-based justification · accurate interpretation in plain language · honest statement of limitations.

---

###  Quick reference: methods you may need
These are either new or only briefly seen in class. Everything else you need was used in Labs 11-15.

| Method | What it does | Tiny example |
|:--|:--|:--|
| `df.duplicated()` / `df.drop_duplicates()` | Flags / removes rows identical to an earlier row (`keep=False` marks *all* copies) | `df.duplicated().sum()` |
| `s.value_counts()` | Counts each distinct value (`dropna=False` also counts NaN; `normalize=True` gives proportions) | `df["gender"].value_counts()` |
| `df.sort_values(by, ascending=...)` | Sorts rows by one or more columns | `df.sort_values(["age","bmi"], ascending=[False, True])` |
| `s.str.strip()`, `s.str.lower()` | Cleans text in a column | `df["gender"].str.strip().str.lower()` |
| `df.copy()` | Makes an independent copy | `df_clean = df.copy()` |
| `df.reset_index(drop=True)` | Renumbers the row labels 0, 1, 2, ... | `df.reset_index(drop=True)` |
| `np.where(cond, a, b)` | Picks `a` where the condition is True, else `b` (can be nested) | `np.where(df["age"] > 60, "old", "young")` |
| `s.isin([...])` | True where the value is one of the listed values | `df["work_type"].isin(["Private","Govt_job"])` |
| `df.isnull().any(axis=1)` | True for rows that contain at least one NaN | `df[df.isnull().any(axis=1)]` |
| `s.unique()` / `.tolist()` | The distinct values, as an array / list | `df["gender"].unique().tolist()` |
| `s.round(n)` | Rounds to `n` decimals | `(x * 100).round(2)` |

### Setup
Run this cell first. It imports the libraries you will use throughout the assignment.

In [1]:
import numpy as np
import pandas as pd

# Optional: show all columns when displaying a DataFrame
pd.set_option("display.max_columns", None)

---
## Section A: Dataset Exploration  (7 Marks)
**Level:** Basic  ·

Get to know the dataset before touching it. Use the **raw** DataFrame `df` here and do **not** modify it.

### Q1. Loading the data and taking a first look
**[3 Marks]** · *Coding* · Marks split: (a)+(b) 1 · (c) 1 · (d) 1

**What you must do**<br>
(a) Load `healthcare.csv` into a DataFrame called `df` using `pd.read_csv()`.<br>
(b) Using `df.shape`, print one sentence in the form: *"The dataset has ___ rows and ___ columns."* (use an f-string).<br>
(c) Print the names of all columns as a Python list.<br>
(d) Display the first 5 rows, the last 4 rows, and 5 randomly sampled rows (use `random_state=42` so that everybody gets the same sample).

**Why this matters**
Before any analysis you must confirm that the file loaded correctly and know its size and columns. A wrong assumption here silently spoils everything that follows.

**Expected output / answer**
One printed sentence, a list of column names, and three small tables (head, tail, sample).

In [2]:
# (a) Load the data into df
df = pd.read_csv("healthcare.csv")

In [3]:
# (b) Print the shape in a sentence
rows, cols = df.shape
print(f"The dataset has {rows} rows and {cols} columns.")

The dataset has 1260 rows and 12 columns.

In [4]:
# (c) Print the list of column names
print(df.columns.tolist())

['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'Residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke']

In [5]:
# (d) Show head, tail and a random sample
print("First 5 rows:")
display(df.head(5))

print("Last 4 rows:")
display(df.tail(4))

print("5 random rows (random_state=42):")
display(df.sample(5, random_state=42))

First 5 rows:

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,40041,MALE,31.0,0,0,No,Self-employed,Rural,64.85,23.0,Unknown,0
1,55244,MALE,40.0,0,0,NaN,NaN,Rural,65.29,28.3,never smoked,0
2,70992,female,8.0,0,0,No,children,Urban,74.42,22.5,Unknown,0
3,38207,female,79.0,1,0,Yes,Self-employed,Rural,76.64,19.5,never smoked,0
4,8541,female,75.0,0,0,Yes,Govt_job,Rural,94.77,27.2,never smoked,0

Last 4 rows:

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
1256,28183,female,13.0,0,0,No,children,Urban,75.78,23.6,NaN,0
1257,2548,female,81.0,0,0,Yes,Self-employed,Urban,95.84,21.5,never smoked,1
1258,51746,female,37.0,0,0,Yes,Govt_job,Rural,67.07,27.4,never smoked,0
1259,17308,female,72.0,1,0,Yes,Private,Urban,221.79,30.0,NaN,1

5 random rows (random_state=42):

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
76,65643,female,7.0,0,0,No,children,Urban,156.82,17.3,NaN,0
1026,61171,female,31.0,0,0,No,Private,Rural,59.63,NaN,never smoked,0
43,53010,MALE,82.0,0,0,Yes,Self-employed,Rural,56.75,21.0,NaN,0
666,71318,MALE,67.0,0,0,Yes,Govt_job,Rural,244.28,29.4,formerly smoked,0
529,47196,MALE,42.0,0,0,Yes,Private,Rural,110.68,32.4,formerly smoked,0

### Q2. Data types, structure and summary statistics
**[1 Mark]** · *Coding* · Marks split: all four outputs = 1

**What you must do**<br>
Display:<br>
(i) the data type of every column (`.dtypes`),<br>
(ii) `df.info()`,<br>
(iii) `df.describe()`, and<br> 
(iv) `df.describe(include="all")`.

**Why this matters**
Data types decide which operations are valid. `info()` shows non-null counts (the first clue about missing data) and `describe()` gives a quick numeric summary.

**Expected output / answer**
Four outputs. Look carefully at how (iii) and (iv) differ: you will need this in the next question.

In [6]:
# (i) dtypes
print(df.dtypes)

id                     int64
gender                   str
age                  float64
hypertension           int64
heart_disease          int64
ever_married             str
work_type                str
Residence_type           str
avg_glucose_level    float64
bmi                  float64
smoking_status           str
stroke                 int64
dtype: object

In [7]:
# (ii) info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1260 non-null   int64
 1   gender             1260 non-null   str
 2   age                1260 non-null   float64
 3   hypertension       1260 non-null   int64
 4   heart_disease      1260 non-null   int64
 5   ever_married       1196 non-null   str
 6   work_type          1196 non-null   str
 7   Residence_type     1260 non-null   str
 8   avg_glucose_level  1260 non-null   float64
 9   bmi                1084 non-null   float64
 10  smoking_status     1132 non-null   str
 11  stroke             1260 non-null   int64
dtypes: float64(3), int64(4), str(5)
memory usage: 118.3 KB

In [8]:
# (iii) describe (numeric columns)
df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,1260.000000,1260.000000,1260.000000,1260.000000,1260.000000,1084.000000,1260.000000
mean,38671.734127,42.960762,0.114286,0.053968,105.362762,28.773893,0.062698
std,39924.682880,22.888033,0.318284,0.226045,44.281491,7.826631,0.242516
min,67.000000,0.080000,0.000000,0.000000,55.230000,11.500000,0.000000
25%,18637.250000,24.000000,0.000000,0.000000,77.812500,23.300000,0.000000
50%,37341.500000,45.000000,0.000000,0.000000,91.935000,28.200000,0.000000
75%,55567.000000,61.000000,0.000000,0.000000,112.482500,33.100000,0.000000
max,729150.000000,82.000000,1.000000,1.000000,266.590000,71.900000,1.000000

In [9]:
# (iv) describe (all columns)
df.describe(include="all")

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
count,1260.000000,1260,1260.000000,1260.000000,1260.000000,1196,1196,1260,1260.000000,1084.000000,1132,1260.000000
unique,NaN,3,NaN,NaN,NaN,2,5,2,NaN,NaN,4,NaN
top,NaN,female,NaN,NaN,NaN,Yes,Private,Urban,NaN,NaN,never smoked,NaN
freq,NaN,733,NaN,NaN,NaN,788,687,631,NaN,NaN,423,NaN
mean,38671.734127,NaN,42.960762,0.114286,0.053968,NaN,NaN,NaN,105.362762,28.773893,NaN,0.062698
std,39924.682880,NaN,22.888033,0.318284,0.226045,NaN,NaN,NaN,44.281491,7.826631,NaN,0.242516
min,67.000000,NaN,0.080000,0.000000,0.000000,NaN,NaN,NaN,55.230000,11.500000,NaN,0.000000
25%,18637.250000,NaN,24.000000,0.000000,0.000000,NaN,NaN,NaN,77.812500,23.300000,NaN,0.000000
50%,37341.500000,NaN,45.000000,0.000000,0.000000,NaN,NaN,NaN,91.935000,28.200000,NaN,0.000000
75%,55567.000000,NaN,61.000000,0.000000,0.000000,NaN,NaN,NaN,112.482500,33.100000,NaN,0.000000
max,729150.000000,NaN,82.000000,1.000000,1.000000,NaN,NaN,NaN,266.590000,71.900000,NaN,1.000000

### Q3. Understanding the columns
**[3 Marks]** · *Written* · Marks split: (a) 1 · (b) 1 · (c) 1

**What you must do**
Using the outputs of the previous two questions:<br>
(a) Complete the table in your answer cell by classifying each of the 12 columns as **Identifier**, **Numerical (continuous)**, **Binary (0/1)** or **Categorical (text)**.<br>
(b) `id` is stored as a number, yet its mean is meaningless, while the mean of `stroke` is meaningful. Explain what the mean of a 0/1 column represents, and what the mean of `id` would tell us.<br>
(c) From `describe()`, name **two** values in `age`, `bmi` or `avg_glucose_level` that look unusual or worth checking later. Give the column, the value, and why it caught your eye.

**Why this matters**<br>
Choosing the right kind of summary depends on the kind of variable. Averaging an ID, or treating a 0/1 flag like a measurement, are classic beginner mistakes.

**Expected output / answer**
A completed table plus 4-6 sentences in simple language.

_Write your answer here (double-click to edit):_

**(a)**

| Column | Type |
|---|---|
| id | Identifier |
| gender | Categorical (text) |
| age | Numerical (continuous) |
| hypertension | Binary (0/1) |
| heart_disease | Binary (0/1) |
| ever_married | Categorical (text: Yes/No) |
| work_type | Categorical (text) |
| Residence_type | Categorical (text) |
| avg_glucose_level | Numerical (continuous) |
| bmi | Numerical (continuous) |
| smoking_status | Categorical (text) |
| stroke | Binary (0/1) |

**(b)** In a 0/1 column the mean is the **share (proportion) of patients who have a 1**. The mean of `stroke` is 0.0627, so about **6.27%** of the 1,260 raw rows are stroke patients (and the mean of `hypertension` is 0.114, so 11.4% have high blood pressure). The mean of `id` (38,671.73) tells us nothing: an ID is only a label, like a roll number. Adding up labels and dividing has no real-world meaning.

**(c)** Two values worth checking:
1. `bmi` maximum = **71.9**. The 75th percentile is only 33.1, so this value is far above the rest. (The minimum, 11.5, is also very low.)
2. `avg_glucose_level` maximum = **266.59**. The median is 91.94 but the mean is 105.36, so a few very high values are pulling the mean up.

(Also noticed: `age` minimum = 0.08, which is about one month old. This is not an error, because the data dictionary says infants are stored as fractions of a year.)

---
## Section B: Data Quality Assessment  (9 Marks)
**Level:** Basic  ·

Inspect the raw `df` and report problems. **Do not modify `df` in this section.**

### Q4. Missing values
**[3 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 1

**What you must do**<br>
(a) Count the missing values in every column (`isnull().sum()`).<br>
(b) Calculate the **percentage** of missing values per column (rounded to 2 decimals). Show only columns that have at least one missing value, highest percentage first.<br>
(c) How many rows have **at least one** missing value? (hint: `isnull().any(axis=1)`)<br>
(d) Count the rows in which `ever_married` **and** `work_type` are both missing at the same time.

Then, in the written cell: which column has the highest percentage of missing data, and what does your result in (d) suggest about *how* the missing values may have arisen?

**Why this matters**
You cannot choose a sensible cleaning strategy until you know how much is missing, where it is missing, and whether the gaps follow a pattern.

**Expected output / answer**
Counts, a sorted percentage table, two single numbers, and 2-3 sentences of explanation.

In [10]:
# (a) Missing value count per column
print(df.isnull().sum())

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married          64
work_type             64
Residence_type         0
avg_glucose_level      0
bmi                  176
smoking_status       128
stroke                 0
dtype: int64

In [11]:
# (b) Percentage missing (only columns with missing values, sorted high to low)
missing_pct = (df.isnull().mean() * 100).round(2)
missing_pct = missing_pct[missing_pct > 0].sort_values(ascending=False)
print(missing_pct)

bmi               13.97
smoking_status    10.16
ever_married       5.08
work_type          5.08
dtype: float64

In [12]:
# (c) Rows with at least one missing value
rows_with_nan = df.isnull().any(axis=1).sum()
print("Rows with at least one missing value:", rows_with_nan)

Rows with at least one missing value: 330

In [13]:
# (d) Rows where ever_married and work_type are both missing
both_missing = (df["ever_married"].isnull() & df["work_type"].isnull()).sum()
print("Rows where ever_married AND work_type are both missing:", both_missing)

# extra check: are the missing rows exactly the same rows?
print("ever_married missing:", df["ever_married"].isnull().sum(),
      "| work_type missing:", df["work_type"].isnull().sum())

Rows where ever_married AND work_type are both missing: 64
ever_married missing: 64 | work_type missing: 64

_Write your answer here (double-click to edit):_

**Highest missing percentage:** `bmi` has the most missing data: **176 values = 13.97%**. Next are `smoking_status` (128 = 10.16%) and `ever_married` and `work_type` (64 each = 5.08%). In total **330 rows** (more than a quarter of the data) have at least one missing value.

**What (d) suggests:** `ever_married` and `work_type` are missing in exactly the **same 64 rows** (64 in each column, and 64 rows where both are missing). If values were lost at random, we would expect the two columns to be missing in different rows. Since they go missing together, there is probably one common cause: for example, the part of the registration form with marital and job details was not filled in for these patients, or these records came from a different source that did not have these fields. So the missing values are not random, they follow a pattern.

### Q5. Inconsistent entries and data types
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Written 2

**What you must do**<br>
(a) For each of `gender`, `ever_married`, `work_type`, `Residence_type` and `smoking_status`, print the frequency of each category **including missing values** (`value_counts(dropna=False)`).<br>
(b) Print the unique values of `gender` as a Python list (`.unique().tolist()`) and read them *character by character*.

Written answer: list **at least three** data-quality problems you found in the categorical columns or data types. For each one state the column, what is wrong, and which type of problem it is (formatting / placeholder-for-missing / rare category / wrong data type). Also answer: is the fractional `age` (e.g. 1.48) an error? Defend your answer.

**Why this matters**
Inconsistent labels such as `male` vs `MALE ` look identical to a human but are different groups to Pandas, so every `groupby` result becomes wrong without any error message.

**Expected output / answer**
Frequency tables, a printed list, and a short structured list of problems.

>**Hint:** Some problems are invisible when a table is displayed. Printing a list shows quotes around each value, which reveals spaces.

In [14]:
# (a) Frequency of categories in each text column
for col in ["gender", "ever_married", "work_type", "Residence_type", "smoking_status"]:
    print(f"--- {col} ---")
    print(df[col].value_counts(dropna=False))
    print()

--- gender ---
gender
female     733
MALE       526
Other        1
Name: count, dtype: int64

--- ever_married ---
ever_married
Yes    788
No     408
NaN     64
Name: count, dtype: int64

--- work_type ---
work_type
Private          687
Self-employed    182
children         176
Govt_job         149
NaN               64
Never_worked       2
Name: count, dtype: int64

--- Residence_type ---
Residence_type
Urban    631
Rural    629
Name: count, dtype: int64

--- smoking_status ---
smoking_status
never smoked       423
Unknown            347
formerly smoked    189
smokes             173
NaN                128
Name: count, dtype: int64

In [15]:
# (b) Unique values of gender, shown as a list
# Printing a list shows quotes, so hidden spaces become visible
print(df["gender"].unique().tolist())

['MALE ', 'female ', 'Other ']

_Write your answer here (double-click to edit):_

**Data-quality problems found**

1. **`gender` - formatting problem.** The values are `'MALE '`, `'female '` and `'Other '`: they have a hidden **space at the end** and the capital letters are inconsistent (`MALE` vs `female`). Pandas would treat `'MALE '` and `'male'` as different groups. This is only visible when the list is printed with quotes.
2. **`gender` - rare category.** `'Other '` appears in only **1 row** out of 1,260. One patient is too few to say anything about that group.
3. **`smoking_status` - placeholder for missing.** There are **347** rows with the text `"Unknown"` (27.5%) *and* **128** real missing values (NaN). The same problem (we do not know) is written in two different ways.
4. **`ever_married` and `work_type` - real missing values.** 64 NaN in each column (5.08%).
5. **`work_type` - rare category.** `Never_worked` appears in only **2 rows**.
6. **`id` - wrong data type.** `id` is stored as a number (int64), but it is a label. It should be text.

**Is the fractional age an error?** No. The data dictionary says infants are recorded as fractions of a year. For example 0.08 years is about 1 month, and 1.48 years is about 17-18 months. Rounding these to whole numbers would wrongly make babies look like 0 or 1 year old and lose information.

### Q6. Duplicate records and the ID check
**[3 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 1

**What you must do**<br>
(a) How many rows of `df` are **exact duplicates** of an earlier row?<br>
(b) Display 6 of the duplicated rows, sorted by `id`, so that **both copies** of a record appear (hint: look up the `keep` parameter of `.duplicated()`).<br>
(c) Create `temp = df.drop_duplicates()` (do not overwrite `df`). Do any `id` values *still* appear more than once in `temp`? If so, display those rows.<br>

Written answer: are the rows you found in (c) real duplicates? What would you do with them and why? Why did `drop_duplicates()` not remove them?

**Why this matters**
Duplicates inflate counts and bias averages. But an *ID* that repeats does not automatically mean a repeated *patient*, and you must check before deleting anything.

**Expected output / answer**
A number, a small table of duplicated pairs, a table of repeated-ID rows, and 3-4 sentences.

In [16]:
# (a) Number of exact duplicate rows
print("Exact duplicate rows:", df.duplicated().sum())

Exact duplicate rows: 60

In [17]:
# (b) Show both copies of some duplicated rows (sorted by id)
# keep=False marks ALL copies (the first one too), not just the later ones
dup_rows = df[df.duplicated(keep=False)].sort_values("id")
dup_rows.head(6)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
1071,809,MALE,13.0,0,0,No,children,Urban,71.73,NaN,Unknown,0
1222,809,MALE,13.0,0,0,No,children,Urban,71.73,NaN,Unknown,0
761,1577,female,17.0,0,0,No,Private,Urban,70.01,43.0,Unknown,0
1240,1577,female,17.0,0,0,No,Private,Urban,70.01,43.0,Unknown,0
785,2304,MALE,51.0,0,0,Yes,Govt_job,Rural,95.19,24.3,smokes,0
1254,2304,MALE,51.0,0,0,Yes,Govt_job,Rural,95.19,24.3,smokes,0

In [18]:
# (c) Remove exact duplicates into temp, then check for repeated ids
temp = df.drop_duplicates()
print("Shape after drop_duplicates:", temp.shape)

# ids that still appear more than once
repeated_ids = temp[temp["id"].duplicated(keep=False)].sort_values("id")
print("Rows with a repeated id:", len(repeated_ids))
repeated_ids

Shape after drop_duplicates: (1200, 12)
Rows with a repeated id: 3

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
171,729150,MALE,21.0,0,0,NaN,NaN,Rural,65.09,23.5,never smoked,0
395,729150,MALE,59.0,0,0,Yes,Govt_job,Urban,70.04,31.4,never smoked,0
405,729150,female,31.0,0,0,No,Private,Urban,108.89,52.3,Unknown,0

_Write your answer here (double-click to edit):_

**(a)-(b)** There are **60 exact duplicate rows** (every column is identical to an earlier row). After `drop_duplicates()` the shape goes from (1260, 12) to (1200, 12).

**(c) Are the repeated ids real duplicates?** No. The id **729150** appears 3 times, but these are **three different people**: a 21-year-old man, a 59-year-old man and a 31-year-old woman, with different glucose, BMI and so on. Also 729150 is a very large id (the 75th percentile of id is only about 55,567), so it may be a placeholder or a data-entry mistake.

**What I would do:** I would **keep all three rows**, because deleting them would remove real patients. I would give them new unique ids (or flag them) and ask the hospital where this id came from.

**Why `drop_duplicates()` did not remove them:** it only removes rows that are identical in **every** column. These three rows share the id but differ in other columns, so Pandas correctly treats them as different records.

---
## Section C: Data Cleaning and Preprocessing  (14 Marks)
**Level:** Basic to Intermediate  ·

Now you fix the problems you found. **Work on a copy** so the raw data stays available for comparison: from Q7 onward you will create and use **`df_clean`**, and every later section uses `df_clean`.

There is rarely one single correct way to clean data. **Marks for the 'justify' parts are awarded for evidence-based reasoning**, not for matching a model answer. Always back your choice with something you actually observed in the data (a count, a mean/median, an age range...).

*Reminder from Lab: assign filled columns back with* `df_clean["col"] = df_clean["col"].fillna(value)`.

### Q7. Standardising column names and text values
**[2 Marks]** · *Coding* · Marks split: (a) 1 · (b) 1

**What you must do**<br>
(a) Create `df_clean = df.copy()`. Rename **all** column names to lowercase using `rename(str.lower, axis="columns")`. Print the new column list.<br>
(b) Standardise the `gender` column in `df_clean`: remove leading/trailing spaces (`.str.strip()`) and convert to lowercase (`.str.lower()`). Verify with `value_counts()`.

**Why this matters**
After this step `male` and `MALE ` become the same group, and all column names follow one style. Remember: from now on the column is called `residence_type`.

**Expected output / answer**
The new column list, and a `gender` frequency table with exactly three clean categories.

In [19]:
# (a) Copy and rename columns
df_clean = df.copy()
df_clean = df_clean.rename(str.lower, axis="columns")
print(df_clean.columns.tolist())

['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke']

In [20]:
# (b) Clean the gender column
df_clean["gender"] = df_clean["gender"].str.strip().str.lower()
print(df_clean["gender"].value_counts())

gender
female    733
male      526
other       1
Name: count, dtype: int64

### Q8. Removing duplicate records
**[2 Marks]** · *Coding + Written* · Marks split: Code 1 · Written 1

**What you must do**<br>
(a) Remove the exact duplicate rows from `df_clean`. Print the shape **before** and **after**, then reset the row labels with `reset_index(drop=True)`.

Written answer:<br> (i) Why is it better to remove duplicates **before** filling missing values with a mean, median or mode?<br> (ii) Why was it sensible to standardise `gender` (previous question) **before** removing duplicates?

**Why this matters**
Duplicated rows count some patients twice, which distorts every statistic and the most-frequent value (mode) that you may use for filling.

**Expected output / answer**
Two shapes, one cleaned DataFrame, and 3-4 sentences of reasoning.

In [21]:
# (a) Drop duplicates, print shapes before/after, reset the index
print("Shape before:", df_clean.shape)
df_clean = df_clean.drop_duplicates().reset_index(drop=True)
print("Shape after :", df_clean.shape)

Shape before: (1260, 12)
Shape after : (1200, 12)

_Write your answer here (double-click to edit):_

**(i) Why remove duplicates before filling missing values?** A mean, median or mode is calculated from all rows. If 60 patients are counted twice, they have double weight and can shift the fill value. Here, for example, the median or mode of a column could be slightly different with the 60 extra copies. If we fill first, we would copy a value that was calculated from wrong (repeated) data into many rows. It is cleaner to fix the rows first and then calculate the fill values from the correct data.

**(ii) Why standardise `gender` before removing duplicates?** Pandas compares text exactly. `'MALE '` and `'male'` look the same to us, but they are different strings, so two copies of the same patient written differently would **not** be found as duplicates. After `strip()` and `lower()`, such rows become identical and can be removed. (In this dataset the 60 duplicates were already exact copies, so the count stayed 60, but doing the steps in this order is the safe habit.)

### Q9. Handling missing numeric values: `bmi`
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Justification 2

**What you must do**<br>
(a) Look at `df_clean["bmi"].describe()` and compute its **mean** and **median**.<br>
(b) Fill the missing `bmi` values with the statistic you choose. Print the number of missing values **before** and **after**.

Justification: why did you choose that statistic rather than the other one? Use evidence from (a). Also mention one weakness of giving every patient the *same* replacement value (think about a 5-year-old and a 70-year-old).

**Why this matters**
`bmi` is missing for about 14% of patients, the largest gap in the dataset. Dropping them all would waste a lot of data, so you need a defensible fill value.

**Expected output / answer**
Descriptive statistics, before/after missing counts, and a justified choice (4-5 sentences).

> **Hint:** Look at the maximum and minimum of `bmi`, and compare mean with median. Which statistic is pulled around by extreme values?

In [22]:
# (a) Explore bmi
print(df_clean["bmi"].describe())
bmi_mean = df_clean["bmi"].mean()
bmi_median = df_clean["bmi"].median()
print("\nMean  :", round(bmi_mean, 2))
print("Median:", round(bmi_median, 2))

# Extra evidence: does bmi depend on age? (checked BEFORE filling)
age_band = pd.cut(df_clean["age"], bins=[0, 18, 40, 60, 100], right=False)
print("\nbmi by age band (before filling):")
print(df_clean.groupby(age_band, observed=True)["bmi"].agg(["count", "mean", "median"]).round(2))

# (b) Fill the missing values and show the count before and after
print("\nMissing bmi before:", df_clean["bmi"].isnull().sum())
df_clean["bmi"] = df_clean["bmi"].fillna(bmi_median)
print("Missing bmi after :", df_clean["bmi"].isnull().sum())

count    1033.000000
mean       28.755179
std         7.877637
min        11.500000
25%        23.300000
50%        28.200000
75%        33.100000
max        71.900000
Name: bmi, dtype: float64

Mean  : 28.76
Median: 28.2

bmi by age band (before filling):
           count   mean  median
age
[0, 18)      191  20.73    19.4
[18, 40)     266  29.62    28.6
[40, 60)     316  32.01    30.7
[60, 100)    260  29.81    28.9

Missing bmi before: 167
Missing bmi after : 0

_Write your answer here (double-click to edit):_

**Choice: median (28.2).**

**Evidence from (a):** the mean is 28.76 and the median is 28.20, close to each other, but the maximum is **71.9** while the 75th percentile is only 33.1. A few very high BMI values pull the mean up (the mean is a little above the median), while the median is not affected by extreme values. The median is also a real, typical value in the data, so it is the safer choice.

**Weakness of one value for everyone:** BMI depends on age. In the age-band table, children under 18 have a median BMI of about **19.4**, while patients aged 40-59 have a median of about **30.7**. Filling every missing value with 28.2 makes missing children look too heavy and missing middle-aged patients look too light. It also creates a spike at 28.2: 167 rows (13.9%) now have exactly the same value, which slightly reduces the spread (std). A better method would be to fill with the median of each age group.

### Q10. Handling missing categorical values: `ever_married` and `work_type`
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Justification 2

**What you must do**<br>
(a) Look at the rows where `ever_married` is missing: show the summary of their `age` (`describe()`), and count how many are **under 18**.<br>
(b) Choose **one** strategy and apply it to both `ever_married` and `work_type`:
   - fill with the most frequent value (mode), **or**
   - fill with a new label such as `"Not recorded"`, **or**
   - drop these rows, **or**
   - another strategy you can defend.

Justification: explain your choice using what you saw in (a), and state one risk or side-effect of your choice.

**Why this matters**
For text columns there is no mean or median. A careless fill (for example 'Yes' for every missing marital status) can create impossible records such as a married toddler.

**Expected output / answer**
An age summary, a count, your cleaned columns (show remaining nulls = 0 or explain), and a justified decision (4-5 sentences).

In [23]:
# (a) Who are the patients with missing ever_married?
missing_married = df_clean[df_clean["ever_married"].isnull()]
print("Number of patients:", len(missing_married))
print(missing_married["age"].describe())
print("\nAged under 18:", (missing_married["age"] < 18).sum())

# Would dropping these rows lose stroke cases?
print("Strokes among them:", missing_married["stroke"].sum(), "of", df_clean["stroke"].sum(), "in the whole data")

# Are the same rows also missing work_type?
print("Also missing work_type:", missing_married["work_type"].isnull().sum())

# For comparison: what do the known under-18 patients look like?
kids = df_clean[df_clean["age"] < 18]
print("\nKnown under-18 patients - ever_married:")
print(kids["ever_married"].value_counts(dropna=False))
print("\nKnown under-18 patients - work_type:")
print(kids["work_type"].value_counts(dropna=False))

Number of patients: 60
count    60.000000
mean     46.584000
std      23.770454
min       0.800000
25%      28.250000
50%      47.500000
75%      67.000000
max      82.000000
Name: age, dtype: float64

Aged under 18: 8
Strokes among them: 9 of 75 in the whole data
Also missing work_type: 60

Known under-18 patients - ever_married:
ever_married
No     205
NaN      8
Name: count, dtype: int64

Known under-18 patients - work_type:
work_type
children         170
Private           30
NaN                8
Self-employed      3
Never_worked       2
Name: count, dtype: int64

In [24]:
# (b) Apply your chosen strategy to ever_married and work_type
# Strategy: fill with a new label "Not recorded" (do NOT guess Yes / Private)
df_clean["ever_married"] = df_clean["ever_married"].fillna("Not recorded")
df_clean["work_type"] = df_clean["work_type"].fillna("Not recorded")

print("Remaining nulls -> ever_married:", df_clean["ever_married"].isnull().sum(),
      "| work_type:", df_clean["work_type"].isnull().sum())
print()
print(df_clean["ever_married"].value_counts())
print()
print(df_clean["work_type"].value_counts())

Remaining nulls -> ever_married: 0 | work_type: 0

ever_married
Yes             751
No              389
Not recorded     60
Name: count, dtype: int64

work_type
Private          649
Self-employed    177
children         170
Govt_job         142
Not recorded      60
Never_worked       2
Name: count, dtype: int64

_Write your answer here (double-click to edit):_

**What (a) showed:** The 60 patients with missing `ever_married` (and the same 60 are missing `work_type`) are of **all ages**: from 0.8 to 82 years, with a median of 47.5. **8 of them are under 18.** Among patients whose values are known, **all 205 under-18 patients have `ever_married = No`** and most of them have `work_type = children`.

**Strategy chosen:** fill both columns with a new label, **`"Not recorded"`**.

**Why:** If I used the mode (`Yes` and `Private`), then the 8 children would become "married" and "Private workers", which is impossible. Dropping the 60 rows would lose 5% of the data, and it would also remove **9 stroke patients out of 75** (12% of all stroke cases), which is a big loss for a stroke study. A new label keeps all rows and does not invent any information.

**Risk / side-effect:** `"Not recorded"` becomes a new category in later `groupby` results, but it is a mixture of children, adults and seniors, not a real group. Its results must be read carefully, and it should not be compared like a real work type.

### Q11. `smoking_status`: real missing values vs the placeholder `Unknown`
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Justification 2

**What you must do**<br>
This column has **both** real missing values (NaN) **and** the text `"Unknown"`.<br>
(a) Show `value_counts(dropna=False)` for `smoking_status`.<br>
(b) Using filtering, compare the distribution of `smoking_status` for **children** (`age < 18`) and **adults** (`age >= 18`).<br>
(c) Decide how to treat `"Unknown"` and NaN, and apply it. *(In Labs 13 and 14 you replaced "Unknown" with NaN and then filled the NaN. Think about whether that is appropriate here.)*

Justification: defend your decision using the evidence from (b). Do you treat NaN and "Unknown" as the same thing? Why or why not?

**Why this matters**
Replacing a meaningful 'Unknown' with the most common value would invent data. This question practises looking for the *reason* behind missingness before choosing a fix.

**Expected output / answer**
Frequency tables for all/children/adults, your cleaned column, and a justification of 4-6 sentences.

In [25]:
# (a) Overall frequency (including NaN)
print(df_clean["smoking_status"].value_counts(dropna=False))

smoking_status
never smoked       400
Unknown            332
formerly smoked    180
smokes             168
NaN                120
Name: count, dtype: int64

In [26]:
# (b) Children vs adults
children = df_clean[df_clean["age"] < 18]
adults = df_clean[df_clean["age"] >= 18]

print("CHILDREN (age < 18): n =", len(children))
print(pd.DataFrame({
    "count": children["smoking_status"].value_counts(dropna=False),
    "percent": (children["smoking_status"].value_counts(dropna=False, normalize=True) * 100).round(2)
}))

print("\nADULTS (age >= 18): n =", len(adults))
print(pd.DataFrame({
    "count": adults["smoking_status"].value_counts(dropna=False),
    "percent": (adults["smoking_status"].value_counts(dropna=False, normalize=True) * 100).round(2)
}))

CHILDREN (age < 18): n = 213
                 count  percent
smoking_status
Unknown            158    74.18
never smoked        28    13.15
NaN                 21     9.86
formerly smoked      5     2.35
smokes               1     0.47

ADULTS (age >= 18): n = 987
                 count  percent
smoking_status
never smoked       372    37.69
formerly smoked    175    17.73
Unknown            174    17.63
smokes             167    16.92
NaN                 99    10.03

In [27]:
# (c) Apply your decision
# - "Unknown" is kept as it is (it is a real answer: status was not known / not asked)
# - real NaN is given its own label "Not recorded" (the value was lost, so it stays separate)
df_clean["smoking_status"] = df_clean["smoking_status"].fillna("Not recorded")

print("Remaining nulls:", df_clean["smoking_status"].isnull().sum())
print(df_clean["smoking_status"].value_counts())

Remaining nulls: 0
smoking_status
never smoked       400
Unknown            332
formerly smoked    180
smokes             168
Not recorded       120
Name: count, dtype: int64

_Write your answer here (double-click to edit):_

**Evidence from (b):** `"Unknown"` is **not spread evenly**: it is **74.18%** of children (158 of 213) but only **17.63%** of adults (174 of 987). The real missing values (NaN) are about the **same** in both groups: 9.86% in children and 10.03% in adults.

**Decision:**
- Keep **`"Unknown"`** as its own category. It looks like a systematic answer connected with age (smoking status was probably not asked or not applicable for many children), so it carries information. If I replaced it with NaN and then filled it with the mode (`never smoked`), I would be inventing a smoking history for 332 patients, including 158 young children.
- Treat the **NaN** separately and label it **`"Not recorded"`**. These look like random gaps (the same share in every age group), where the answer existed but was lost.

**Same or different?** Different. `"Unknown"` follows a pattern linked to age, while NaN looks random. So I keep them separate. (If a simpler table is needed later, both can be joined as "status not known", but that should be a conscious choice.) **Side-effect:** the column now has five categories and two of them mean "we do not know", so results for these two groups must not be read as real smoking behaviour.

### Q12. Final check and saving the cleaned file
**[1 Mark]** · *Coding* · Marks split: all parts = 1

**What you must do**<br>
(a) Show the missing-value count per column, the shape and the data types of `df_clean`.<br>
(b) Convert `id` to text (`astype(str)`), because an identifier is a label, not a number.<br>
(c) Save `df_clean` as `healthcare_clean.csv` (`index=False`), read it back into `df_check`, and print whether `df_check.shape == df_clean.shape`.

**Why this matters**
A cleaning job is only finished when you have *verified* the result, and saving the file lets others reuse it (as in Lab 14).

**Expected output / answer**
Zero (or justified) missing values, the correct dtypes, and `True` for the shape check.

In [28]:
# (a) Verify the cleaned data
print("Missing values per column:")
print(df_clean.isnull().sum())
print("\nShape:", df_clean.shape)
print("\nData types:")
print(df_clean.dtypes)

Missing values per column:
id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

Shape: (1200, 12)

Data types:
id                     int64
gender                   str
age                  float64
hypertension           int64
heart_disease          int64
ever_married             str
work_type                str
residence_type           str
avg_glucose_level    float64
bmi                  float64
smoking_status           str
stroke                 int64
dtype: object

In [29]:
# (b) Convert id to text
df_clean["id"] = df_clean["id"].astype(str)
print(df_clean["id"].dtype)
df_clean[["id"]].head()

str

      id
0  40041
1  55244
2  70992
3  38207
4   8541

In [30]:
# (c) Save, reload and compare shapes
df_clean.to_csv("healthcare_clean.csv", index=False)
df_check = pd.read_csv("healthcare_clean.csv")
print("df_check.shape:", df_check.shape, "| df_clean.shape:", df_clean.shape)
print("Shapes equal:", df_check.shape == df_clean.shape)

df_check.shape: (1200, 12) | df_clean.shape: (1200, 12)
Shapes equal: True

---
## Section D: Core Pandas Operations  (9 Marks)
**Level:** Intermediate  ·

From here on use the cleaned DataFrame **`df_clean`**. (If your cleaning dropped rows, call `df_clean.reset_index(drop=True)` first so that row labels run from 0 upwards.)

### Q13. Selecting data with `loc` and `iloc`
**[2 Marks]** · *Coding + Written* · Marks split: Code 1 · Written 1

**What you must do**<br>
(a) Using **`loc`**, select the rows labelled **10 to 14** and the columns `age`, `bmi` and `stroke`.<br>
(b) Using **`iloc`**, select exactly the **same** rows and columns by integer position. (Print `df_clean.columns.to_list()` first to find the column positions.)

Written answer: in your own words, what is the difference between `loc` and `iloc`, and why did you have to use a different end number in (b) than in (a)?

**Why this matters**
Selecting precisely the rows and columns you need is the foundation of every later step. `loc` and `iloc` look similar but treat the end of a slice differently.

**Expected output / answer**
Two identical 5-row, 3-column tables and a 2-3 sentence explanation.

In [ ]:
# (a) loc  (labels 10 to 14 - BOTH ends included)

     age   bmi  stroke
10  37.0  27.4       0
11   3.0  19.9       0
12  60.0  36.4       0
13  51.0  20.9       0
14  57.0  28.2       0

In [ ]:
# (b) iloc (positions - the end number is NOT included)
# age = position 2, bmi = position 9, stroke = position 11

['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke']

     age   bmi  stroke
10  37.0  27.4       0
11   3.0  19.9       0
12  60.0  36.4       0
13  51.0  20.9       0
14  57.0  28.2       0

_Write your answer here (double-click to edit):_

- **`loc`** selects by **labels** (the row label and column name). The end of the slice **is included**, so `10:14` gives rows 10, 11, 12, 13 and 14 (5 rows).
- **`iloc`** selects by **integer position** (like a list index). The end of the slice is **not included**, so to get the same 5 rows I had to write `10:15` (positions 10 to 14).

The columns in (b) were chosen by position (`age` = 2, `bmi` = 9, `stroke` = 11). Both give the same output here because after `reset_index(drop=True)` the row labels are the same as the positions.

### Q14. Filtering rows with conditions
**[3 Marks]** · *Coding* · Marks split: (a) 1 · (b) 1 · (c) 1

**What you must do**<br>
For each part, print **how many** patients match (use `len()`) and display the first 5 matching rows.<br>
(a) Patients aged **60 or above** who have **hypertension** and an `avg_glucose_level` **above 140**. Also calculate what **percentage of this group** had a stroke.<br>
(b) Patients who either **smoke** or **formerly smoked** *and* have **heart disease**.<br>
(c) Patients whose `work_type` is **Private or Govt_job** and who **had a stroke**.<br>

**Why this matters**
Filtering lets you isolate a clinically meaningful group, such as high-risk older patients, and study only them.

**Expected output / answer**
Three counts, three small tables, and one percentage.

> **Hint:** Wrap each condition in parentheses and combine with `&` (and) / `|` (or). The `.isin([...])` method is a neat shortcut for 'is one of these values'.

In [ ]:
# (a) Older, hypertensive, high-glucose patients

Patients matching (a): 29
Stroke rate in this group:  31.03 %

,id,gender,age,hypertension,heart_disease,ever_married,work_type,residence_type,avg_glucose_level,bmi,smoking_status,stroke
92,48775,female,78.0,1,0,Yes,Self-employed,Rural,201.07,21.8,Unknown,0
104,68981,female,71.0,1,0,Yes,Govt_job,Urban,219.80,34.2,formerly smoked,0
119,38493,male,60.0,1,1,Yes,Private,Urban,201.01,28.0,never smoked,0
224,39202,female,61.0,1,1,Not recorded,Not recorded,Urban,237.58,28.2,formerly smoked,0
286,17308,female,72.0,1,0,Yes,Private,Urban,221.79,30.0,Not recorded,1

In [ ]:
# (b) Current or former smokers with heart disease

Patients matching (b): 24

,id,gender,age,hypertension,heart_disease,ever_married,work_type,residence_type,avg_glucose_level,bmi,smoking_status,stroke
14,41940,male,57.0,0,1,Yes,Private,Rural,62.20,28.2,formerly smoked,0
52,54401,male,80.0,0,1,Yes,Self-employed,Urban,252.72,30.5,formerly smoked,1
72,5353,male,52.0,0,1,No,Private,Rural,101.50,31.2,smokes,0
193,53697,male,58.0,0,1,Yes,Private,Rural,225.35,26.5,smokes,0
224,39202,female,61.0,1,1,Not recorded,Not recorded,Urban,237.58,28.2,formerly smoked,0

In [ ]:
# (c) Private/Govt_job workers who had a stroke

Patients matching (c): 47

,id,gender,age,hypertension,heart_disease,ever_married,work_type,residence_type,avg_glucose_level,bmi,smoking_status,stroke
57,64778,male,82.0,0,1,Yes,Private,Rural,208.30,32.5,Unknown,1
96,17013,male,78.0,1,0,No,Private,Urban,113.01,24.0,never smoked,1
115,70042,male,58.0,0,0,Yes,Private,Urban,71.20,28.2,Unknown,1
128,42072,female,50.0,1,0,Yes,Private,Rural,73.18,30.3,Not recorded,1
134,27419,female,59.0,0,0,Yes,Private,Rural,76.15,28.2,Unknown,1

### Q15. Sorting
**[1 Mark]** · *Coding* · Marks split: 1

**What you must do**<br>
Show the **5 oldest patients who had a stroke**. Sort by `age` (largest first) and break ties by `avg_glucose_level` (largest first). Display only the columns `age`, `gender`, `hypertension`, `avg_glucose_level`, `bmi`.

**Why this matters**
Sorting quickly brings the most extreme or most important cases to the top of a table.

**Expected output / answer**
A 5-row, 5-column table.

In [ ]:
# Top 5 oldest stroke patients

       age  gender  hypertension  avg_glucose_level   bmi
57    82.0    male             0             208.30  32.5
1189  82.0    male             0              86.62  29.5
148   81.0    male             0             213.22  26.1
1044  81.0  female             0              95.84  21.5
341   81.0  female             0              81.95  16.9

### Q16. Creating new columns
**[3 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 1

**What you must do**<br>
Add these three columns to `df_clean`:
- `age_group`: **"Child"** if age < 18, **"Adult"** if 18 <= age < 60, **"Senior"** if age >= 60 (hint: nest two `np.where()` calls).
- `high_glucose`: 1 if `avg_glucose_level` > 140, otherwise 0. *(For this assignment treat above 140 mg/dL as 'high'.)*
- `obese`: 1 if `bmi` >= 30, otherwise 0.

Print the frequency of each `age_group`, and display `age`, `age_group`, `avg_glucose_level`, `high_glucose`, `bmi`, `obese` for the first 5 rows.

Written answer: explain in your own words how your nested `np.where` decides the group for a patient aged **45**.

**Why this matters**
Raw numbers are hard to compare across groups. Derived columns such as age groups turn continuous values into meaningful categories that we will use in Sections E and F.

**Expected output / answer**
Three new columns, a frequency table, a 5-row preview, and a short explanation.

In [ ]:
# Create age_group, high_glucose and obese
# nested np.where: first test "age < 18", otherwise test "age < 60", otherwise Senior

age_group
Adult     671
Senior    316
Child     213
Name: count, dtype: int64

    age age_group  avg_glucose_level  high_glucose   bmi  obese
0  31.0     Adult              64.85             0  23.0      0
1  40.0     Adult              65.29             0  28.3      0
2   8.0     Child              74.42             0  22.5      0
3  79.0    Senior              76.64             0  19.5      0
4  75.0    Senior              94.77             0  27.2      0

_Write your answer here (double-click to edit):_

For a patient aged **45**, the outer `np.where` first asks: *is age < 18?* For 45 the answer is **False**, so it moves to the inner `np.where`, which asks: *is age < 60?* The answer is **True**, so the patient is labelled **"Adult"**. The label "Senior" is only given when both questions are False (age 60 or more).

Result: 213 Child, 671 Adult and 316 Senior patients.

---
## Section E: Statistical Analysis  (6 Marks)
**Level:** Intermediate 

Summarise the numerical columns, then judge how trustworthy those summaries are. Use `df_clean`.

### Q17. Descriptive statistics
**[3 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 1

**What you must do**<br>
(a) For `age`, `bmi` and `avg_glucose_level`, build **one summary table** with the **mean, median, min, max and standard deviation** (use `.agg()` on the three columns, rounded to 2 decimals). Separately print the **mode** of each column.<br>
(b) Calculate the **relative spread** of each column as `std / mean`.

Written answer: for `avg_glucose_level`, compare the mean with the median. What does the gap tell you about the shape of the data? Which of the three variables has the largest relative spread, and what does that mean in plain language?

**Why this matters**
The mean alone can mislead. Comparing mean, median and spread tells you whether the 'typical' patient is well described by one number.

**Expected output / answer**
A summary table, three modes, three relative-spread values, and 3-4 sentences.

In [ ]:

# (a) Summary table with agg(), then the modes

          age    bmi  avg_glucose_level
mean    42.86  28.68             105.30
median  45.00  28.20              91.98
min      0.08  11.50              55.23
max     82.00  71.90             266.59
std     22.94   7.31              44.23

Mode of each column:
age -> [59.0]
bmi -> [28.2]
avg_glucose_level -> [80.63, 92.86]

In [ ]:
# (b) Relative spread = std / mean

age                  0.535
bmi                  0.255
avg_glucose_level    0.420
dtype: float64

_Write your answer here (double-click to edit):_

**Mean vs median for `avg_glucose_level`:** the mean (105.30) is clearly higher than the median (91.98), a gap of about 13 mg/dL. This tells us the data is **skewed to the right**: most patients have glucose around 80-110, but a smaller group has very high values (up to 266.59) which pull the mean up. So the median describes the "typical" patient better than the mean.

**Largest relative spread:** `age` (std / mean = **0.535**), followed by glucose (0.420) and bmi (0.255). In plain language, the ages in this dataset are very spread out: babies and 82-year-old patients are in the same table, so one "average age" of 42.86 does not describe most patients well.

**Note:** the mode of `bmi` (28.2) is only the same as the median because I filled 167 missing values with 28.2 in Q9. It is not a "natural" most-common value.

### Q18. Spotting outliers with the IQR rule
**[3 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 1

**What you must do**<br>
(a) For `bmi` and `avg_glucose_level`: compute Q1 and Q3 (`quantile`), the IQR (Q3 - Q1), the lower bound (Q1 - 1.5 x IQR) and the upper bound (Q3 + 1.5 x IQR), and **count** the values outside the bounds.<br>
(b) Display the 5 patients with the **highest** `bmi` (show `age`, `gender`, `bmi`, `stroke`).

Written answer: are these extreme values more likely to be data errors or rare-but-real measurements? Would you remove them? Explain what could go wrong in an analysis of stroke risk if you deleted them.

**Why this matters**
Outliers can distort averages, but in healthcare the extreme patients are often exactly the ones at highest risk, so deleting them blindly can be harmful.

**Expected output / answer**
Bounds and outlier counts for both columns, a 5-row table, and a 3-4 sentence justification.

In [ ]:
# (a) IQR rule for bmi and avg_glucose_level

bmi: Q1=24.20, Q3=32.00, IQR=7.80, lower=12.50, upper=43.70
   outliers: 44 (below: 2, above: 42) = 3.67% of rows

avg_glucose_level: Q1=77.75, Q3=112.48, IQR=34.73, lower=25.66, upper=164.58
   outliers: 138 (below: 0, above: 138) = 11.50% of rows

In [ ]:
# (b) Five highest BMI values

       age  gender   bmi  stroke
481   42.0    male  71.9       0
125   52.0  female  61.6       0
1193  57.0  female  60.9       0
1151  39.0  female  57.9       0
592   46.0    male  57.3       0

_Write your answer here (double-click to edit):_

**IQR results:** `bmi` has bounds 12.50 to 43.70 and **44 outliers** (3.67%, mostly high). `avg_glucose_level` has bounds 25.66 to 164.58 and **138 outliers** (11.5%), all above the upper bound. The highest BMI is 71.9 (a 42-year-old man).

**Error or real?** Most of these look like **rare but real measurements**. A BMI of 71.9 is extremely high, but possible in severe obesity, and glucose above 164 mg/dL is common in people with diabetes. They are not impossible values like a negative age. I cannot be 100% sure from this table, so the unusual BMI values (like 71.9) should be checked against the original hospital records.

**Would I remove them?** No. 138 glucose outliers are 11.5% of the data, and high glucose is exactly the kind of patient we want to study: stroke patients have a mean glucose of 131.22 compared with 103.57 for non-stroke patients. If I deleted the high values, I would remove part of the high-risk patients and **underestimate** the link between glucose and stroke, and the results would look safer than reality.

---
## Section F: Exploratory Analysis and Insights  (18 Marks)
**Level:** Intermediate to Advanced  

Now use `groupby`, `agg` and filtering to look for **patterns**. In this dataset a group's **stroke rate** is simply the mean of the 0/1 column `stroke` for that group (multiply by 100 for a percentage).

*Always support a statement with a number from your own output, and always check the **group size** (`count`) next to every rate.*

### Q19. Frequency distributions and overall stroke prevalence
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Written 2

**What you must do**<br>
(a) For `stroke`, `gender` and `age_group`, print the **percentage** of patients in each category (use `value_counts(normalize=True)`, multiply by 100, round to 2 decimals).

Written answer:<br> (i) What percentage of patients in this dataset had a stroke, and which age group is the largest?<br> (ii) Can you conclude that this same percentage of *all people in the general population* have a stroke? Explain.

**Why this matters**<br>
Frequencies tell you who is in your dataset. Understanding who is in the sample is essential before saying anything about people outside it.

**Expected output / answer**
Three percentage tables and 3-4 sentences.

In [ ]:
# (a) Percentage distributions

--- stroke (%) ---
stroke
0    93.75
1     6.25
Name: proportion, dtype: float64

--- gender (%) ---
gender
female    58.42
male      41.50
other      0.08
Name: proportion, dtype: float64

--- age_group (%) ---
age_group
Adult     55.92
Senior    26.33
Child     17.75
Name: proportion, dtype: float64

_Write your answer here (double-click to edit):_

**(i)** **6.25%** of the patients (75 out of 1,200) had a stroke. The largest age group is **Adult** with **55.92%** of the patients (Senior 26.33%, Child 17.75%).

**(ii)** No. This is data from one hospital, not a random sample of the whole population. Hospital patients are usually sicker than the average person, and the sample is also not balanced (for example 58.42% female). So 6.25% only describes **these 1,200 patients**. We cannot say that the same percentage of all people in the general population have a stroke.

### Q20. Comparing stroke and non-stroke patients
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Written 2

**What you must do**<br>
(a) Group `df_clean` by `stroke` and show the **mean and median** of `age`, `bmi` and `avg_glucose_level` for the two groups (rounded to 2 decimals).

Written answer:<br> (i) Which variable differs most between the two groups?<br> (ii) For `avg_glucose_level`, compare the *difference in means* with the *difference in medians*. What might explain why they are not the same?<br> (iii) Why is it helpful to look at the median as well as the mean here?

**Why this matters**
Comparing groups side by side is the core move of exploratory analysis: it shows which measurements might be linked to the outcome.

**Expected output / answer**
One grouped table and 4-5 sentences with numbers.

In [ ]:
# (a) Groupby stroke with mean and median

          age           bmi        avg_glucose_level
         mean median   mean median              mean  median
stroke
0       41.22   43.0  28.60   28.2            103.57   91.81
1       67.37   70.0  29.83   28.2            131.22  100.98

_Write your answer here (double-click to edit):_

**(i)** `age` differs the most. The mean age of stroke patients is **67.37** against **41.22** for non-stroke patients, about 63% higher. For `avg_glucose_level` the mean is 131.22 vs 103.57 (about 27% higher) and for `bmi` it is 29.83 vs 28.60 (only about 4% higher).

**(ii)** For `avg_glucose_level` the difference in means is **27.65** (131.22 - 103.57), but the difference in medians is only **9.17** (100.98 - 91.81). The two differences are not the same because the mean is pulled up by a group of stroke patients with very high glucose. Most stroke patients are not that high, but a few extreme values raise the mean a lot.

**(iii)** The median shows the "middle" patient and is not changed by a few extreme values. Looking at both tells us whether a difference is true for the typical patient (median) or mainly caused by a few extreme cases (mean). (Note: the bmi medians are both 28.2 partly because the missing values were filled with 28.2.)

### Q21. Stroke rate by health factors
**[4 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 2

**What you must do**<br>
(a) For each of `hypertension`, `heart_disease` and `age_group`, build a table showing the **number of patients (`count`)**, the **number of strokes (`sum`)** and the **stroke rate in %**. (use `groupby(col)["stroke"].agg([...])`)<br>
(b) Calculate **how many times higher** the stroke rate is for patients *with* hypertension than *without*, and the same for heart disease.

Written answer: rank the three factors by the stroke rates you observed. Which group in your tables is the smallest, and why must you be careful when interpreting a high percentage that comes from a small group?

**Why this matters**
Rates (not raw counts) allow a fair comparison between groups of different sizes, and relative comparisons show how strongly a factor is associated with the outcome.

**Expected output / answer**
Three tables, two ratios and a 4-5 sentence interpretation that quotes at least three numbers.

In [ ]:
# (a) Stroke counts and rates by hypertension, heart_disease, age_group

--- hypertension ---
              patients  strokes  stroke_rate_%
hypertension
0                 1063       54           5.08
1                  137       21          15.33

--- heart_disease ---
               patients  strokes  stroke_rate_%
heart_disease
0                  1136       62           5.46
1                    64       13          20.31

--- age_group ---
           patients  strokes  stroke_rate_%
age_group
Adult           671       25           3.73
Child           213        0           0.00
Senior          316       50          15.82

In [ ]:
# (b) Ratio of rates (with vs without)

hypertension: with = 15.33%, without = 5.08%  ->  3.02 times higher
heart_disease: with = 20.31%, without = 5.46%  ->  3.72 times higher

_Write your answer here (double-click to edit):_

**Ranking by stroke rate (highest first):**
1. **Heart disease:** 20.31% (13 of 64) vs 5.46% without, so **3.72 times** higher.
2. **Age group - Senior:** 15.82% (50 of 316). This is 4.2 times the Adult rate of 3.73%, and no child had a stroke (0 of 213).
3. **Hypertension:** 15.33% (21 of 137) vs 5.08% without, so **3.02 times** higher.

**Smallest group:** patients with heart disease: only **64 patients** (13 strokes). The hypertension group is also small (137). A high percentage from a small group is **unstable**: in the heart disease group, one more or one less stroke changes the rate by about 1.6 percentage points (1 out of 64). So the 20.31% could easily be a bit higher or lower with another sample, and the true size of the effect is less certain than for the big groups. Also, these are only associations: older people are more likely to have both heart disease and a stroke, so age may be part of the reason.

### Q22. Is smoking really linked to stroke? Looking beyond the first table
**[4 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 2

**What you must do**<br>
(a) For **all patients**, show for each `smoking_status` the number of patients, the stroke rate (%), and the **mean age**.<br>
(b) Repeat (a) for **seniors only** (`age_group == "Senior"`): number of patients and stroke rate (%) per `smoking_status`.

Written answer: compare (a) and (b). What changed? Explain in simple language why the pattern in (a) may be partly caused by **age** rather than smoking, and say clearly whether this dataset can prove that smoking does or does not cause stroke.

**Why this matters**
A pattern between two variables can be produced by a third one (a *confounder*). Learning to check this is one of the most important habits in data analysis, especially in healthcare.

**Expected output / answer**
Two tables and a 5-6 sentence interpretation quoting numbers from both tables.

> **Hint:** Check which smoking group is oldest on average. Remember that older people have higher stroke rates in general (see the previous question).

In [ ]:
# (a) All patients: count, stroke rate %, mean age by smoking_status

                 patients  stroke_rate_pct  mean_age
smoking_status
Not recorded          120             8.33      40.5
Unknown               332             3.31      28.7
formerly smoked       180            11.67      54.9
never smoked          400             5.75      47.8
smokes                168             5.95      47.8

In [ ]:
# (b) Seniors only: count and stroke rate % by smoking_status

Seniors in total: 316

                 patients  stroke_rate_pct
smoking_status
Not recorded           21            19.05
Unknown                51            13.73
formerly smoked        76            17.11
never smoked          126            15.87
smokes                 42            14.29

_Write your answer here (double-click to edit):_

**What changed from (a) to (b):** In (a), **formerly smoked** patients have the highest stroke rate, **11.67%**, about twice that of **never smoked** (5.75%), and current smokers (5.95%) are almost the same as never smoked. But in (b), among seniors only, the rates are close together: formerly smoked 17.11%, never smoked 15.87%, smokes 14.29%. The gap between formerly smoked and never smoked went from about 2 times to about 1.08 times, and current smokers are now even *lower* than never smokers.

**Why age may explain (a):** In (a), the mean age of the **formerly smoked** group is **54.9**, while never smoked and smokes are both 47.8. The Unknown group is very young (28.7), which is why its stroke rate is low (3.31%). Older people have more strokes anyway (Senior 15.82% vs Adult 3.73%), so a group that is older will look "worse" even if smoking has no effect. When we compare people of a similar age (seniors), most of the pattern disappears. Age is a **confounder**.

**Can this dataset prove that smoking causes (or does not cause) stroke?** No. It is a single snapshot of patients with no follow-up. The senior groups are small (for example only 42 smokers, about 6 strokes), smoking status is missing or Unknown for many patients, and we did not control other factors such as blood pressure. This dataset can show an association, not a cause. It also cannot prove that smoking is harmless.

### Q23. Your own investigation (open-ended)
**[4 Marks]** · *Open-ended (Coding + Written)* · Marks split: Question 1 · Code 1 · Interpretation 1 · Limitation 1

**What you must do**<br>
Design and carry out **one** investigation of your own. It must be a question that is **not** already asked in this assignment. Ideas: gender, residence type or work type vs stroke; glucose level within age groups; hypertension **and** heart disease together; whether obese patients have higher glucose.

In your answer:<br>
1. State your **question** and a one-sentence **hypothesis** (what you expect to find).<br>
2. Write the code. It must use **at least two** of: filtering, `groupby`, `agg`, a new column, sorting.<br>
3. **Interpret** the output in 3-4 sentences that quote numbers.<br>
4. State **one limitation** of your analysis.

**Why this matters**
Real data analysis starts with *your* question. This task shows whether you can turn curiosity into a correct Pandas analysis and an honest conclusion.

**Expected output / answer**
A written question and hypothesis, a code cell with output, an interpretation with numbers, and one limitation.

In [48]:
# Question: Do patients who have BOTH hypertension and heart disease have a higher stroke rate
#           than patients with only one of them, and does the pattern stay the same inside the Senior group?
# Hypothesis: Stroke rate will rise step by step: none < one condition < both conditions,
#             and the pattern will still be visible among seniors (so it is not only an age effect).

In [ ]:
# Your code below
# new column: number of conditions each patient has (0, 1 or 2)

ALL PATIENTS
              patients  strokes  mean_age  stroke_rate_pct
n_conditions
1                  173       30      61.6            17.34
2                   14        2      68.6            14.29
0                 1013       43      39.3             4.24

SENIORS ONLY (age >= 60)
              patients  strokes  mean_age  stroke_rate_pct
n_conditions
1                   98       26      72.4            26.53
2                   13        2      70.7            15.38
0                  205       22      70.1            10.73

_Write your interpretation and limitation here (double-click to edit):_

**Question and hypothesis:** Do patients with **both** hypertension and heart disease have a higher stroke rate than patients with only one of them (or none), and does the pattern remain when we look at seniors only? *Hypothesis:* the stroke rate will increase step by step: none < one condition < both conditions, and it will still be visible among seniors.

**Interpretation (with numbers):** Having at least one condition clearly goes with more strokes: patients with no condition have a stroke rate of **4.24%** (43 of 1,013), and patients with one condition have **17.34%** (30 of 173). Among seniors the same pattern is seen: **10.73%** (no condition) vs **26.53%** (one condition), which is about 2.5 times higher, so this is not only an age effect. However, patients with **both** conditions had **14.29%** (2 of 14), which is *lower* than the one-condition group, and among seniors 15.38% (2 of 13). So the first part of my hypothesis (a condition raises the rate) is supported, but the second part (both is the worst) is **not supported** by this data.

**One limitation:** Only **14 patients** (13 seniors) have both conditions, with just 2 strokes. One more or one less stroke would change the rate by about 7 percentage points, so no reliable conclusion about the "both" group can be made.

---
## Section G: Interpretation and Conclusion  (7 Marks)
**Level:** Applied  ·
Time to communicate. Good analysts do not only compute, they explain, and they are careful not to claim more than the data supports.

### Q24. Supported or not supported by this dataset?
**[3 Marks]** · *Coding + Written* · Marks split: 1 mark per statement

**What you must do**<br>
For each statement, decide whether it is **Supported**, **Partly supported** or **Not supported** by this dataset. Justify each decision in 1-2 sentences using **one number** from your analysis. (You may use the code cell as a scratch space to get the numbers.)

1. *"In this dataset, patients aged 60 and above had a higher stroke rate than younger patients."*<br>
2. *"Smoking causes stroke."*<br>
3. *"Men are much more likely than women to have a stroke."*

**Why this matters**
Healthcare conclusions affect real decisions. A good analyst separates what the data shows from what it cannot show.

**Expected output / answer**
Three verdicts, each with a number and a short reason.

In [ ]:
# Scratch space for any numbers you need

Stroke rate, age >= 60: 15.82 % (n = 316 )
Stroke rate, age < 60 : 2.83 % (n = 884 )

Stroke rate by smoking status (all):
                 count   mean
smoking_status
Not recorded       120   8.33
Unknown            332   3.31
formerly smoked    180  11.67
never smoked       400   5.75
smokes             168   5.95

Stroke rate by smoking status (seniors only):
                 count   mean
smoking_status
Not recorded        21  19.05
Unknown             51  13.73
formerly smoked     76  17.11
never smoked       126  15.87
smokes              42  14.29

Stroke by gender:
        count  sum  mean
gender
female    701   41  5.85
male      498   34  6.83
other       1    0  0.00

Stroke rate by gender, seniors only:
        count  sum   mean
gender
female    182   28  15.38
male      134   22  16.42

_Write your answer here (double-click to edit):_

**1.** Verdict: **Supported**
Reason: Patients aged 60 and above had a stroke rate of **15.82%** (n = 316) compared with **2.83%** (n = 884) for younger patients, about 5.6 times higher. (This describes the pattern in this dataset; it does not say age alone is the cause.)

**2.** Verdict: **Not supported**
Reason: Current smokers had a stroke rate of **5.95%**, almost the same as never smokers (**5.75%**). Among seniors it was 14.29% for smokers and 15.87% for never smokers. The data is a one-time snapshot, so it cannot prove that smoking causes stroke (or that it does not).

**3.** Verdict: **Not supported**
Reason: Men had a stroke rate of **6.83%** (34 of 498) and women **5.85%** (41 of 701). The difference is only about 1 percentage point (and 16.42% vs 15.38% among seniors), which is not "much more likely" and could easily be due to chance in a sample of this size.

### Q25. Summary for the hospital manager
**[4 Marks]** · *Written* · Marks split: Findings 2 · Limitations 1 · Plain language, no unsupported claims 1

**What you must do**<br>
Write a short report (**150 to 250 words**) for a hospital manager who has **no** data-science background. It must contain:
- **At least three key findings**, each supported by a number from your analysis;
- **At least two limitations** of the dataset or of your analysis;
- **One recommended next step** (more data, a better data collection practice, or a further analysis).

Use simple language, avoid jargon, and do **not** make claims the data cannot support (for example, do not say that something *causes* a stroke).

**Why this matters**
The final skill of EDA is communication: a correct analysis is useless if the decision maker cannot understand it or if it overstates the evidence.

**Expected output / answer**
One well-organised paragraph or a few short paragraphs (150-250 words).

_Write your report here (double-click to edit):_

**Report for the hospital manager**

We studied the records of 1,200 patients (after removing 60 repeated rows). Of these, 75 patients (6.25%) had a stroke.

**What we found**
1. **Age is the clearest pattern.** Patients aged 60 or above had a stroke rate of 15.8%, compared with 2.8% for younger patients. None of the 213 children had a stroke.
2. **Heart disease and high blood pressure go with more strokes.** The stroke rate was 20.3% for patients with heart disease (5.5% without) and 15.3% for patients with high blood pressure (5.1% without).
3. **Smoking looked risky at first, but this was mostly because of age.** Former smokers were older (average 54.9 years). Among seniors, smokers (14.3%) and non-smokers (15.9%) had similar rates.

**Limitations**
- The data is a one-time snapshot from one hospital, so it shows links, not causes, and the 6.25% cannot be used for the whole population.
- Many values were missing or unknown (BMI for 14% of patients), and some groups are small (only 64 patients with heart disease), so some rates may change a lot with a few patients.

**Recommended next step:** Record BMI, smoking and job details for every patient at registration, give each patient a unique ID, and repeat this analysis with more patients.

---
### End of Assignment