<div align="center">

# MIT Vishwaprayag University, Solapur

## EDA & DV — Assignment 3
#### Healthcare Dataset (Stroke Risk Data)

### Course: B.Tech Semester-III  
</div>


| | |
|:--|:--|
| **Total Marks** | 70 |
| **Dataset** | `healthcare.csv` (place it in the **same folder** as this notebook) |

---

### About this assignment
A hospital has given you a patient dataset and asked you to **check its quality, clean it, and find out what it can (and cannot) tell us** about stroke. The tasks move from basic exploration to open-ended analysis, using the Pandas skills from Labs 11-15 (Series/DataFrame, `loc`/`iloc`, `read_csv`, handling missing values, `describe`, filtering, `groupby`/`agg`, saving files).


### The dataset (data dictionary)
Each row is one patient record.

| Column | Meaning |
|:--|:--|
| `id` | Patient identifier |
| `gender` | Patient's gender |
| `age` | Age in **years** (infants are recorded as fractions, e.g. 0.08) |
| `hypertension` | 1 = patient has high blood pressure, 0 = no |
| `heart_disease` | 1 = patient has heart disease, 0 = no |
| `ever_married` | Whether the patient has ever been married (Yes/No) |
| `work_type` | Type of work (Private, Self-employed, Govt_job, children, Never_worked) |
| `Residence_type` | Rural or Urban |
| `avg_glucose_level` | Average blood glucose level (mg/dL) |
| `bmi` | Body Mass Index (kg/m²) |
| `smoking_status` | never smoked / formerly smoked / smokes / Unknown |
| `stroke` | 1 = patient had a stroke, 0 = no |

### Instructions
1. Write your code in the **code cell** below each question and your written answers in the **markdown cell** (double-click a cell to edit it; press `Shift+Enter` to run/render it).
2. Every question states **what to do**, **why it matters** and the **expected output**. Read all three.
3. For *justify / explain / interpret* parts: write **in your own words and in simple language**, and back every claim with a **number from your own output**. Answers that make claims the data cannot support will lose marks.
4. In the cleaning section there is often **more than one acceptable answer**. Marks are given for *reasoning backed by evidence*, not for guessing the 'expected' method.
5. Add short `#` comments to your code so a reader can follow your thinking. Code you cannot explain may be questioned in a viva.
6. A few helpful methods were not shown in class. They are listed in the reference box below. You may also use the Pandas documentation (`help(pd.DataFrame.method_name)`).
7. Before submitting: **Kernel → Restart & Run All** and make sure the notebook runs from top to bottom without errors. Save as `<RollNo>_EDA_Assignment-3.ipynb`.

> **Marking guide:** correct and efficient Pandas code · clear, evidence-based justification · accurate interpretation in plain language · honest statement of limitations.

---

###  Quick reference: methods you may need
These are either new or only briefly seen in class. Everything else you need was used in Labs 11-15.

| Method | What it does | Tiny example |
|:--|:--|:--|
| `df.duplicated()` / `df.drop_duplicates()` | Flags / removes rows identical to an earlier row (`keep=False` marks *all* copies) | `df.duplicated().sum()` |
| `s.value_counts()` | Counts each distinct value (`dropna=False` also counts NaN; `normalize=True` gives proportions) | `df["gender"].value_counts()` |
| `df.sort_values(by, ascending=...)` | Sorts rows by one or more columns | `df.sort_values(["age","bmi"], ascending=[False, True])` |
| `s.str.strip()`, `s.str.lower()` | Cleans text in a column | `df["gender"].str.strip().str.lower()` |
| `df.copy()` | Makes an independent copy | `df_clean = df.copy()` |
| `df.reset_index(drop=True)` | Renumbers the row labels 0, 1, 2, ... | `df.reset_index(drop=True)` |
| `np.where(cond, a, b)` | Picks `a` where the condition is True, else `b` (can be nested) | `np.where(df["age"] > 60, "old", "young")` |
| `s.isin([...])` | True where the value is one of the listed values | `df["work_type"].isin(["Private","Govt_job"])` |
| `df.isnull().any(axis=1)` | True for rows that contain at least one NaN | `df[df.isnull().any(axis=1)]` |
| `s.unique()` / `.tolist()` | The distinct values, as an array / list | `df["gender"].unique().tolist()` |
| `s.round(n)` | Rounds to `n` decimals | `(x * 100).round(2)` |

### Setup
Run this cell first. It imports the libraries you will use throughout the assignment.

In [1]:
import numpy as np
import pandas as pd

# Optional: show all columns when displaying a DataFrame
pd.set_option("display.max_columns", None)

---
## Section A: Dataset Exploration  (7 Marks)
**Level:** Basic  ·

Get to know the dataset before touching it. Use the **raw** DataFrame `df` here and do **not** modify it.

### Q1. Loading the data and taking a first look
**[3 Marks]** · *Coding* · Marks split: (a)+(b) 1 · (c) 1 · (d) 1

**What you must do**<br>
(a) Load `healthcare.csv` into a DataFrame called `df` using `pd.read_csv()`.<br>
(b) Using `df.shape`, print one sentence in the form: *"The dataset has ___ rows and ___ columns."* (use an f-string).<br>
(c) Print the names of all columns as a Python list.<br>
(d) Display the first 5 rows, the last 4 rows, and 5 randomly sampled rows (use `random_state=42` so that everybody gets the same sample).

**Why this matters**
Before any analysis you must confirm that the file loaded correctly and know its size and columns. A wrong assumption here silently spoils everything that follows.

**Expected output / answer**
One printed sentence, a list of column names, and three small tables (head, tail, sample).

In [100]:
# (a) Load the data into df
df = pd.read_csv("healthcare.csv")
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,40041,MALE,31.0,0,0,No,Self-employed,Rural,64.85,23.0,Unknown,0
1,55244,MALE,40.0,0,0,NaN,NaN,Rural,65.29,28.3,never smoked,0
2,70992,female,8.0,0,0,No,children,Urban,74.42,22.5,Unknown,0
3,38207,female,79.0,1,0,Yes,Self-employed,Rural,76.64,19.5,never smoked,0
4,8541,female,75.0,0,0,Yes,Govt_job,Rural,94.77,27.2,never smoked,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1255,49713,MALE,68.0,0,0,Yes,Private,Rural,116.23,26.1,never smoked,0
1256,28183,female,13.0,0,0,No,children,Urban,75.78,23.6,NaN,0
1257,2548,female,81.0,0,0,Yes,Self-employed,Urban,95.84,21.5,never smoked,1
1258,51746,female,37.0,0,0,Yes,Govt_job,Rural,67.07,27.4,never smoked,0
1259,17308,female,72.0,1,0,Yes,Private,Urban,221.79,30.0,NaN,1

In [101]:
# (b) Print the shape in a sentence
rows, cols = df.shape
print(f"The dataset has {rows} rows and {cols} columns.")

The dataset has 1260 rows and 12 columns.

In [ ]:
# (c) Print the list of column names
print(df.columns.tolist())

In [149]:
# (d) Show head, tail and a random sample
print("First 5 rows:")
display(df.head(5))

print("Last 4 rows:")
display(df.tail(4))

print("5 random rows (random_state=42):")
display(df.sample(5, random_state=42))

First 5 rows:

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,40041,MALE,31.0,0,0,No,Self-employed,Rural,64.85,23.0,Unknown,0
1,55244,MALE,40.0,0,0,NaN,NaN,Rural,65.29,28.3,never smoked,0
2,70992,female,8.0,0,0,No,children,Urban,74.42,22.5,Unknown,0
3,38207,female,79.0,1,0,Yes,Self-employed,Rural,76.64,19.5,never smoked,0
4,8541,female,75.0,0,0,Yes,Govt_job,Rural,94.77,27.2,never smoked,0

Last 4 rows:

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
1256,28183,female,13.0,0,0,No,children,Urban,75.78,23.6,NaN,0
1257,2548,female,81.0,0,0,Yes,Self-employed,Urban,95.84,21.5,never smoked,1
1258,51746,female,37.0,0,0,Yes,Govt_job,Rural,67.07,27.4,never smoked,0
1259,17308,female,72.0,1,0,Yes,Private,Urban,221.79,30.0,NaN,1

5 random rows (random_state=42):

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
76,65643,female,7.0,0,0,No,children,Urban,156.82,17.3,NaN,0
1026,61171,female,31.0,0,0,No,Private,Rural,59.63,NaN,never smoked,0
43,53010,MALE,82.0,0,0,Yes,Self-employed,Rural,56.75,21.0,NaN,0
666,71318,MALE,67.0,0,0,Yes,Govt_job,Rural,244.28,29.4,formerly smoked,0
529,47196,MALE,42.0,0,0,Yes,Private,Rural,110.68,32.4,formerly smoked,0

### Q2. Data types, structure and summary statistics
**[1 Mark]** · *Coding* · Marks split: all four outputs = 1

**What you must do**<br>
Display:<br>
(i) the data type of every column (`.dtypes`),<br>
(ii) `df.info()`,<br>
(iii) `df.describe()`, and<br> 
(iv) `df.describe(include="all")`.

**Why this matters**
Data types decide which operations are valid. `info()` shows non-null counts (the first clue about missing data) and `describe()` gives a quick numeric summary.

**Expected output / answer**
Four outputs. Look carefully at how (iii) and (iv) differ: you will need this in the next question.

In [150]:
# (i) dtypes

print(df.dtypes)

id                     int64
gender                   str
age                  float64
hypertension           int64
heart_disease          int64
ever_married             str
work_type                str
Residence_type           str
avg_glucose_level    float64
bmi                  float64
smoking_status           str
stroke                 int64
dtype: object

In [105]:
# (ii) info

In [106]:
# (iii) describe (numeric columns)

In [107]:
# (iv) describe (all columns)

### Q3. Understanding the columns
**[3 Marks]** · *Written* · Marks split: (a) 1 · (b) 1 · (c) 1

**What you must do**
Using the outputs of the previous two questions:<br>
(a) Complete the table in your answer cell by classifying each of the 12 columns as **Identifier**, **Numerical (continuous)**, **Binary (0/1)** or **Categorical (text)**.<br>
(b) `id` is stored as a number, yet its mean is meaningless, while the mean of `stroke` is meaningful. Explain what the mean of a 0/1 column represents, and what the mean of `id` would tell us.<br>
(c) From `describe()`, name **two** values in `age`, `bmi` or `avg_glucose_level` that look unusual or worth checking later. Give the column, the value, and why it caught your eye.

**Why this matters**<br>
Choosing the right kind of summary depends on the kind of variable. Averaging an ID, or treating a 0/1 flag like a measurement, are classic beginner mistakes.

**Expected output / answer**
A completed table plus 4-6 sentences in simple language.

_Write your answer here (double-click to edit):_

**(a)**

| Column | Type |
|---|---|
| id | |
| gender | |
| age | |
| hypertension | |
| heart_disease | |
| ever_married | |
| work_type | |
| Residence_type | |
| avg_glucose_level | |
| bmi | |
| smoking_status | |
| stroke | |

**(b)**

**(c)**

---
## Section B: Data Quality Assessment  (9 Marks)
**Level:** Basic  ·

Inspect the raw `df` and report problems. **Do not modify `df` in this section.**

### Q4. Missing values
**[3 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 1

**What you must do**<br>
(a) Count the missing values in every column (`isnull().sum()`).<br>
(b) Calculate the **percentage** of missing values per column (rounded to 2 decimals). Show only columns that have at least one missing value, highest percentage first.<br>
(c) How many rows have **at least one** missing value? (hint: `isnull().any(axis=1)`)<br>
(d) Count the rows in which `ever_married` **and** `work_type` are both missing at the same time.

Then, in the written cell: which column has the highest percentage of missing data, and what does your result in (d) suggest about *how* the missing values may have arisen?

**Why this matters**
You cannot choose a sensible cleaning strategy until you know how much is missing, where it is missing, and whether the gaps follow a pattern.

**Expected output / answer**
Counts, a sorted percentage table, two single numbers, and 2-3 sentences of explanation.

In [108]:
# (a) Missing value count per column

In [109]:
# (b) Percentage missing (only columns with missing values, sorted high to low)

In [110]:
# (c) Rows with at least one missing value

In [111]:
# (d) Rows where ever_married and work_type are both missing

_Write your answer here (double-click to edit):_

### Q5. Inconsistent entries and data types
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Written 2

**What you must do**<br>
(a) For each of `gender`, `ever_married`, `work_type`, `Residence_type` and `smoking_status`, print the frequency of each category **including missing values** (`value_counts(dropna=False)`).<br>
(b) Print the unique values of `gender` as a Python list (`.unique().tolist()`) and read them *character by character*.

Written answer: list **at least three** data-quality problems you found in the categorical columns or data types. For each one state the column, what is wrong, and which type of problem it is (formatting / placeholder-for-missing / rare category / wrong data type). Also answer: is the fractional `age` (e.g. 1.48) an error? Defend your answer.

**Why this matters**
Inconsistent labels such as `male` vs `MALE ` look identical to a human but are different groups to Pandas, so every `groupby` result becomes wrong without any error message.

**Expected output / answer**
Frequency tables, a printed list, and a short structured list of problems.

>**Hint:** Some problems are invisible when a table is displayed. Printing a list shows quotes around each value, which reveals spaces.

In [112]:
# (a) Frequency of categories in each text column
for col in ["gender", "ever_married", "work_type", "Residence_type", "smoking_status"]:
    pass  # replace this line

In [113]:
# (b) Unique values of gender, shown as a list

_Write your answer here (double-click to edit):_

### Q6. Duplicate records and the ID check
**[3 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 1

**What you must do**<br>
(a) How many rows of `df` are **exact duplicates** of an earlier row?<br>
(b) Display 6 of the duplicated rows, sorted by `id`, so that **both copies** of a record appear (hint: look up the `keep` parameter of `.duplicated()`).<br>
(c) Create `temp = df.drop_duplicates()` (do not overwrite `df`). Do any `id` values *still* appear more than once in `temp`? If so, display those rows.<br>

Written answer: are the rows you found in (c) real duplicates? What would you do with them and why? Why did `drop_duplicates()` not remove them?

**Why this matters**
Duplicates inflate counts and bias averages. But an *ID* that repeats does not automatically mean a repeated *patient*, and you must check before deleting anything.

**Expected output / answer**
A number, a small table of duplicated pairs, a table of repeated-ID rows, and 3-4 sentences.

In [ ]:
# (a) Number of exact duplicate rows
duplicate

In [115]:
# (b) Show both copies of some duplicated rows (sorted by id)

In [116]:
# (c) Remove exact duplicates into temp, then check for repeated ids
temp = None  # replace None with your code

_Write your answer here (double-click to edit):_

---
## Section C: Data Cleaning and Preprocessing  (14 Marks)
**Level:** Basic to Intermediate  ·

Now you fix the problems you found. **Work on a copy** so the raw data stays available for comparison: from Q7 onward you will create and use **`df_clean`**, and every later section uses `df_clean`.

There is rarely one single correct way to clean data. **Marks for the 'justify' parts are awarded for evidence-based reasoning**, not for matching a model answer. Always back your choice with something you actually observed in the data (a count, a mean/median, an age range...).

*Reminder from Lab: assign filled columns back with* `df_clean["col"] = df_clean["col"].fillna(value)`.

### Q7. Standardising column names and text values
**[2 Marks]** · *Coding* · Marks split: (a) 1 · (b) 1

**What you must do**<br>
(a) Create `df_clean = df.copy()`. Rename **all** column names to lowercase using `rename(str.lower, axis="columns")`. Print the new column list.<br>
(b) Standardise the `gender` column in `df_clean`: remove leading/trailing spaces (`.str.strip()`) and convert to lowercase (`.str.lower()`). Verify with `value_counts()`.

**Why this matters**
After this step `male` and `MALE ` become the same group, and all column names follow one style. Remember: from now on the column is called `residence_type`.

**Expected output / answer**
The new column list, and a `gender` frequency table with exactly three clean categories.

In [ ]:


# (a) Copy and rename columns
df_clean = df.copy()
df_clean = df_clean.rename(str.lower, axis="columns")
print(df_clean.columns.tolist())

In [ ]:
# (b) Clean the gender column
df_clean["gender"] = df_clean["gender"].str.strip().str.lower()
print(df_clean["gender"].value_counts())

### Q8. Removing duplicate records
**[2 Marks]** · *Coding + Written* · Marks split: Code 1 · Written 1

**What you must do**<br>
(a) Remove the exact duplicate rows from `df_clean`. Print the shape **before** and **after**, then reset the row labels with `reset_index(drop=True)`.

Written answer:<br> (i) Why is it better to remove duplicates **before** filling missing values with a mean, median or mode?<br> (ii) Why was it sensible to standardise `gender` (previous question) **before** removing duplicates?

**Why this matters**
Duplicated rows count some patients twice, which distorts every statistic and the most-frequent value (mode) that you may use for filling.

**Expected output / answer**
Two shapes, one cleaned DataFrame, and 3-4 sentences of reasoning.

In [ ]:
# (a) Drop duplicates, print shapes before/after, reset the index
print

_Write your answer here (double-click to edit):_

### Q9. Handling missing numeric values: `bmi`
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Justification 2

**What you must do**<br>
(a) Look at `df_clean["bmi"].describe()` and compute its **mean** and **median**.<br>
(b) Fill the missing `bmi` values with the statistic you choose. Print the number of missing values **before** and **after**.

Justification: why did you choose that statistic rather than the other one? Use evidence from (a). Also mention one weakness of giving every patient the *same* replacement value (think about a 5-year-old and a 70-year-old).

**Why this matters**
`bmi` is missing for about 14% of patients, the largest gap in the dataset. Dropping them all would waste a lot of data, so you need a defensible fill value.

**Expected output / answer**
Descriptive statistics, before/after missing counts, and a justified choice (4-5 sentences).

> **Hint:** Look at the maximum and minimum of `bmi`, and compare mean with median. Which statistic is pulled around by extreme values?

In [120]:
# (a) Explore bmi


# (b) Fill the missing values and show the count before and after

_Write your answer here (double-click to edit):_

### Q10. Handling missing categorical values: `ever_married` and `work_type`
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Justification 2

**What you must do**<br>
(a) Look at the rows where `ever_married` is missing: show the summary of their `age` (`describe()`), and count how many are **under 18**.<br>
(b) Choose **one** strategy and apply it to both `ever_married` and `work_type`:
   - fill with the most frequent value (mode), **or**
   - fill with a new label such as `"Not recorded"`, **or**
   - drop these rows, **or**
   - another strategy you can defend.

Justification: explain your choice using what you saw in (a), and state one risk or side-effect of your choice.

**Why this matters**
For text columns there is no mean or median. A careless fill (for example 'Yes' for every missing marital status) can create impossible records such as a married toddler.

**Expected output / answer**
An age summary, a count, your cleaned columns (show remaining nulls = 0 or explain), and a justified decision (4-5 sentences).

In [121]:
# (a) Who are the patients with missing ever_married?

In [122]:
# (b) Apply your chosen strategy to ever_married and work_type

_Write your answer here (double-click to edit):_

### Q11. `smoking_status`: real missing values vs the placeholder `Unknown`
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Justification 2

**What you must do**<br>
This column has **both** real missing values (NaN) **and** the text `"Unknown"`.<br>
(a) Show `value_counts(dropna=False)` for `smoking_status`.<br>
(b) Using filtering, compare the distribution of `smoking_status` for **children** (`age < 18`) and **adults** (`age >= 18`).<br>
(c) Decide how to treat `"Unknown"` and NaN, and apply it. *(In Labs 13 and 14 you replaced "Unknown" with NaN and then filled the NaN. Think about whether that is appropriate here.)*

Justification: defend your decision using the evidence from (b). Do you treat NaN and "Unknown" as the same thing? Why or why not?

**Why this matters**
Replacing a meaningful 'Unknown' with the most common value would invent data. This question practises looking for the *reason* behind missingness before choosing a fix.

**Expected output / answer**
Frequency tables for all/children/adults, your cleaned column, and a justification of 4-6 sentences.

In [123]:
# (a) Overall frequency (including NaN)

In [124]:
# (b) Children vs adults

In [125]:
# (c) Apply your decision

_Write your answer here (double-click to edit):_

### Q12. Final check and saving the cleaned file
**[1 Mark]** · *Coding* · Marks split: all parts = 1

**What you must do**<br>
(a) Show the missing-value count per column, the shape and the data types of `df_clean`.<br>
(b) Convert `id` to text (`astype(str)`), because an identifier is a label, not a number.<br>
(c) Save `df_clean` as `healthcare_clean.csv` (`index=False`), read it back into `df_check`, and print whether `df_check.shape == df_clean.shape`.

**Why this matters**
A cleaning job is only finished when you have *verified* the result, and saving the file lets others reuse it (as in Lab 14).

**Expected output / answer**
Zero (or justified) missing values, the correct dtypes, and `True` for the shape check.

In [126]:
# (a) Verify the cleaned data

In [127]:
# (b) Convert id to text

In [128]:
# (c) Save, reload and compare shapes

---
## Section D: Core Pandas Operations  (9 Marks)
**Level:** Intermediate  ·

From here on use the cleaned DataFrame **`df_clean`**. (If your cleaning dropped rows, call `df_clean.reset_index(drop=True)` first so that row labels run from 0 upwards.)

### Q13. Selecting data with `loc` and `iloc`
**[2 Marks]** · *Coding + Written* · Marks split: Code 1 · Written 1

**What you must do**<br>
(a) Using **`loc`**, select the rows labelled **10 to 14** and the columns `age`, `bmi` and `stroke`.<br>
(b) Using **`iloc`**, select exactly the **same** rows and columns by integer position. (Print `df_clean.columns.to_list()` first to find the column positions.)

Written answer: in your own words, what is the difference between `loc` and `iloc`, and why did you have to use a different end number in (b) than in (a)?

**Why this matters**
Selecting precisely the rows and columns you need is the foundation of every later step. `loc` and `iloc` look similar but treat the end of a slice differently.

**Expected output / answer**
Two identical 5-row, 3-column tables and a 2-3 sentence explanation.

In [129]:
# (a) loc

In [130]:
# (b) iloc

_Write your answer here (double-click to edit):_

### Q14. Filtering rows with conditions
**[3 Marks]** · *Coding* · Marks split: (a) 1 · (b) 1 · (c) 1

**What you must do**<br>
For each part, print **how many** patients match (use `len()`) and display the first 5 matching rows.<br>
(a) Patients aged **60 or above** who have **hypertension** and an `avg_glucose_level` **above 140**. Also calculate what **percentage of this group** had a stroke.<br>
(b) Patients who either **smoke** or **formerly smoked** *and* have **heart disease**.<br>
(c) Patients whose `work_type` is **Private or Govt_job** and who **had a stroke**.<br>

**Why this matters**
Filtering lets you isolate a clinically meaningful group, such as high-risk older patients, and study only them.

**Expected output / answer**
Three counts, three small tables, and one percentage.

> **Hint:** Wrap each condition in parentheses and combine with `&` (and) / `|` (or). The `.isin([...])` method is a neat shortcut for 'is one of these values'.

In [131]:
# (a) Older, hypertensive, high-glucose patients

In [132]:
# (b) Current or former smokers with heart disease

In [133]:
# (c) Private/Govt_job workers who had a stroke

### Q15. Sorting
**[1 Mark]** · *Coding* · Marks split: 1

**What you must do**<br>
Show the **5 oldest patients who had a stroke**. Sort by `age` (largest first) and break ties by `avg_glucose_level` (largest first). Display only the columns `age`, `gender`, `hypertension`, `avg_glucose_level`, `bmi`.

**Why this matters**
Sorting quickly brings the most extreme or most important cases to the top of a table.

**Expected output / answer**
A 5-row, 5-column table.

In [134]:
# Top 5 oldest stroke patients

### Q16. Creating new columns
**[3 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 1

**What you must do**<br>
Add these three columns to `df_clean`:
- `age_group`: **"Child"** if age < 18, **"Adult"** if 18 <= age < 60, **"Senior"** if age >= 60 (hint: nest two `np.where()` calls).
- `high_glucose`: 1 if `avg_glucose_level` > 140, otherwise 0. *(For this assignment treat above 140 mg/dL as 'high'.)*
- `obese`: 1 if `bmi` >= 30, otherwise 0.

Print the frequency of each `age_group`, and display `age`, `age_group`, `avg_glucose_level`, `high_glucose`, `bmi`, `obese` for the first 5 rows.

Written answer: explain in your own words how your nested `np.where` decides the group for a patient aged **45**.

**Why this matters**
Raw numbers are hard to compare across groups. Derived columns such as age groups turn continuous values into meaningful categories that we will use in Sections E and F.

**Expected output / answer**
Three new columns, a frequency table, a 5-row preview, and a short explanation.

In [135]:
# Create age_group, high_glucose and obese

_Write your answer here (double-click to edit):_

---
## Section E: Statistical Analysis  (6 Marks)
**Level:** Intermediate 

Summarise the numerical columns, then judge how trustworthy those summaries are. Use `df_clean`.

### Q17. Descriptive statistics
**[3 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 1

**What you must do**<br>
(a) For `age`, `bmi` and `avg_glucose_level`, build **one summary table** with the **mean, median, min, max and standard deviation** (use `.agg()` on the three columns, rounded to 2 decimals). Separately print the **mode** of each column.<br>
(b) Calculate the **relative spread** of each column as `std / mean`.

Written answer: for `avg_glucose_level`, compare the mean with the median. What does the gap tell you about the shape of the data? Which of the three variables has the largest relative spread, and what does that mean in plain language?

**Why this matters**
The mean alone can mislead. Comparing mean, median and spread tells you whether the 'typical' patient is well described by one number.

**Expected output / answer**
A summary table, three modes, three relative-spread values, and 3-4 sentences.

In [136]:
cols = ["age", "bmi", "avg_glucose_level"]

# (a) Summary table with agg(), then the modes

In [137]:
# (b) Relative spread = std / mean

_Write your answer here (double-click to edit):_

### Q18. Spotting outliers with the IQR rule
**[3 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 1

**What you must do**<br>
(a) For `bmi` and `avg_glucose_level`: compute Q1 and Q3 (`quantile`), the IQR (Q3 - Q1), the lower bound (Q1 - 1.5 x IQR) and the upper bound (Q3 + 1.5 x IQR), and **count** the values outside the bounds.<br>
(b) Display the 5 patients with the **highest** `bmi` (show `age`, `gender`, `bmi`, `stroke`).

Written answer: are these extreme values more likely to be data errors or rare-but-real measurements? Would you remove them? Explain what could go wrong in an analysis of stroke risk if you deleted them.

**Why this matters**
Outliers can distort averages, but in healthcare the extreme patients are often exactly the ones at highest risk, so deleting them blindly can be harmful.

**Expected output / answer**
Bounds and outlier counts for both columns, a 5-row table, and a 3-4 sentence justification.

In [138]:
# (a) IQR rule for bmi and avg_glucose_level
for col in ["bmi", "avg_glucose_level"]:
    pass  # replace this line

In [139]:
# (b) Five highest BMI values

_Write your answer here (double-click to edit):_

---
## Section F: Exploratory Analysis and Insights  (18 Marks)
**Level:** Intermediate to Advanced  

Now use `groupby`, `agg` and filtering to look for **patterns**. In this dataset a group's **stroke rate** is simply the mean of the 0/1 column `stroke` for that group (multiply by 100 for a percentage).

*Always support a statement with a number from your own output, and always check the **group size** (`count`) next to every rate.*

### Q19. Frequency distributions and overall stroke prevalence
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Written 2

**What you must do**<br>
(a) For `stroke`, `gender` and `age_group`, print the **percentage** of patients in each category (use `value_counts(normalize=True)`, multiply by 100, round to 2 decimals).

Written answer:<br> (i) What percentage of patients in this dataset had a stroke, and which age group is the largest?<br> (ii) Can you conclude that this same percentage of *all people in the general population* have a stroke? Explain.

**Why this matters**<br>
Frequencies tell you who is in your dataset. Understanding who is in the sample is essential before saying anything about people outside it.

**Expected output / answer**
Three percentage tables and 3-4 sentences.

In [140]:
# (a) Percentage distributions

_Write your answer here (double-click to edit):_

### Q20. Comparing stroke and non-stroke patients
**[3 Marks]** · *Coding + Written* · Marks split: Code 1 · Written 2

**What you must do**<br>
(a) Group `df_clean` by `stroke` and show the **mean and median** of `age`, `bmi` and `avg_glucose_level` for the two groups (rounded to 2 decimals).

Written answer:<br> (i) Which variable differs most between the two groups?<br> (ii) For `avg_glucose_level`, compare the *difference in means* with the *difference in medians*. What might explain why they are not the same?<br> (iii) Why is it helpful to look at the median as well as the mean here?

**Why this matters**
Comparing groups side by side is the core move of exploratory analysis: it shows which measurements might be linked to the outcome.

**Expected output / answer**
One grouped table and 4-5 sentences with numbers.

In [141]:
# (a) Groupby stroke with mean and median

_Write your answer here (double-click to edit):_

### Q21. Stroke rate by health factors
**[4 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 2

**What you must do**<br>
(a) For each of `hypertension`, `heart_disease` and `age_group`, build a table showing the **number of patients (`count`)**, the **number of strokes (`sum`)** and the **stroke rate in %**. (use `groupby(col)["stroke"].agg([...])`)<br>
(b) Calculate **how many times higher** the stroke rate is for patients *with* hypertension than *without*, and the same for heart disease.

Written answer: rank the three factors by the stroke rates you observed. Which group in your tables is the smallest, and why must you be careful when interpreting a high percentage that comes from a small group?

**Why this matters**
Rates (not raw counts) allow a fair comparison between groups of different sizes, and relative comparisons show how strongly a factor is associated with the outcome.

**Expected output / answer**
Three tables, two ratios and a 4-5 sentence interpretation that quotes at least three numbers.

In [142]:
# (a) Stroke counts and rates by hypertension, heart_disease, age_group
for col in ["hypertension", "heart_disease", "age_group"]:
    pass  # replace this line

In [143]:
# (b) Ratio of rates (with vs without)

_Write your answer here (double-click to edit):_

### Q22. Is smoking really linked to stroke? Looking beyond the first table
**[4 Marks]** · *Coding + Written* · Marks split: Code 2 · Written 2

**What you must do**<br>
(a) For **all patients**, show for each `smoking_status` the number of patients, the stroke rate (%), and the **mean age**.<br>
(b) Repeat (a) for **seniors only** (`age_group == "Senior"`): number of patients and stroke rate (%) per `smoking_status`.

Written answer: compare (a) and (b). What changed? Explain in simple language why the pattern in (a) may be partly caused by **age** rather than smoking, and say clearly whether this dataset can prove that smoking does or does not cause stroke.

**Why this matters**
A pattern between two variables can be produced by a third one (a *confounder*). Learning to check this is one of the most important habits in data analysis, especially in healthcare.

**Expected output / answer**
Two tables and a 5-6 sentence interpretation quoting numbers from both tables.

> **Hint:** Check which smoking group is oldest on average. Remember that older people have higher stroke rates in general (see the previous question).

In [144]:
# (a) All patients: count, stroke rate %, mean age by smoking_status

In [145]:
# (b) Seniors only: count and stroke rate % by smoking_status

_Write your answer here (double-click to edit):_

### Q23. Your own investigation (open-ended)
**[4 Marks]** · *Open-ended (Coding + Written)* · Marks split: Question 1 · Code 1 · Interpretation 1 · Limitation 1

**What you must do**<br>
Design and carry out **one** investigation of your own. It must be a question that is **not** already asked in this assignment. Ideas: gender, residence type or work type vs stroke; glucose level within age groups; hypertension **and** heart disease together; whether obese patients have higher glucose.

In your answer:<br>
1. State your **question** and a one-sentence **hypothesis** (what you expect to find).<br>
2. Write the code. It must use **at least two** of: filtering, `groupby`, `agg`, a new column, sorting.<br>
3. **Interpret** the output in 3-4 sentences that quote numbers.<br>
4. State **one limitation** of your analysis.

**Why this matters**
Real data analysis starts with *your* question. This task shows whether you can turn curiosity into a correct Pandas analysis and an honest conclusion.

**Expected output / answer**
A written question and hypothesis, a code cell with output, an interpretation with numbers, and one limitation.

In [146]:
# Question: 
# Hypothesis:

In [147]:
# Your code below

_Write your interpretation and limitation here (double-click to edit):_

**Question and hypothesis:**

**Interpretation (with numbers):**

**One limitation:**

---
## Section G: Interpretation and Conclusion  (7 Marks)
**Level:** Applied  ·
Time to communicate. Good analysts do not only compute, they explain, and they are careful not to claim more than the data supports.

### Q24. Supported or not supported by this dataset?
**[3 Marks]** · *Coding + Written* · Marks split: 1 mark per statement

**What you must do**<br>
For each statement, decide whether it is **Supported**, **Partly supported** or **Not supported** by this dataset. Justify each decision in 1-2 sentences using **one number** from your analysis. (You may use the code cell as a scratch space to get the numbers.)

1. *"In this dataset, patients aged 60 and above had a higher stroke rate than younger patients."*<br>
2. *"Smoking causes stroke."*<br>
3. *"Men are much more likely than women to have a stroke."*

**Why this matters**
Healthcare conclusions affect real decisions. A good analyst separates what the data shows from what it cannot show.

**Expected output / answer**
Three verdicts, each with a number and a short reason.

In [148]:
# Scratch space for any numbers you need (e.g. a groupby on gender)

_Write your answer here (double-click to edit):_

**1.** Verdict: 
Reason: 

**2.** Verdict: 
Reason: 

**3.** Verdict: 
Reason:

### Q25. Summary for the hospital manager
**[4 Marks]** · *Written* · Marks split: Findings 2 · Limitations 1 · Plain language, no unsupported claims 1

**What you must do**<br>
Write a short report (**150 to 250 words**) for a hospital manager who has **no** data-science background. It must contain:
- **At least three key findings**, each supported by a number from your analysis;
- **At least two limitations** of the dataset or of your analysis;
- **One recommended next step** (more data, a better data collection practice, or a further analysis).

Use simple language, avoid jargon, and do **not** make claims the data cannot support (for example, do not say that something *causes* a stroke).

**Why this matters**
The final skill of EDA is communication: a correct analysis is useless if the decision maker cannot understand it or if it overstates the evidence.

**Expected output / answer**
One well-organised paragraph or a few short paragraphs (150-250 words).

_Write your report here (double-click to edit):_

---
### End of Assignment